import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const vi: Record<string, string> = {
  // Navigation
  "nav.home": "Trang Chủ",
  "nav.program": "Chương Trình",
  "nav.forStudents": "Dành Cho Học Sinh",
  "nav.forParents": "Dành Cho Phụ Huynh",
  "nav.aiPractice": "Luyện Tập với AI",
  "nav.booking": "Đặt Lịch với Mentor",
  "nav.parentDashboard": "Bảng Điều Khiển Phụ Huynh",
  "nav.login": "Đăng nhập",
  "nav.register": "Đăng ký",
  "nav.allPrograms": "Tất cả chương trình",

  // Hero
  "hero.title": "Nâng Trình Giao Tiếp Tiếng Anh với",
  "hero.ai": "AI",
  "hero.and": "và",
  "hero.nativeMentor": "Mentor Bản Xứ",
  "hero.subtitle":
    "Một giải pháp khoa học và toàn diện giúp bạn vượt qua nỗi sợ để tự tin giao tiếp và đạt được điểm số mơ ước.",
  "hero.cta": "Khám phá điều gì đang cản trở bạn",
  "hero.painPoint1": "Em không dám giao tiếp vì sợ nói sai",
  "hero.painPoint2": "Em ít được luyện nói trên lớp",
  "hero.painPoint3": "Em luôn cảm thấy căng thẳng khi nói tiếng Anh",

  // Evidence
  "evidence.title": "Chuyên môn uy tín, nền tảng khoa học vững chắc",
  "evidence.ivyLeague": "Xây dựng bởi các chuyên gia từ các trường Ivy League - Mỹ",
  "evidence.cefr": "Bám sát chuẩn CEFR A2–B1* (tương đương IELTS 3.0–5.0)**",
  "evidence.cefrNote1":
    "* CEFR là chuẩn năng lực tiếng Anh quốc tế được sử dụng trong chương trình học và các kỳ thi như TOEFL, IELTS.",
  "evidence.cefrNote2": "** theo khung quy đổi của Cambridge English.",
  "evidence.flcas": "Dựa trên thang đo S-FLCAS***",
  "evidence.flcasNote":
    "*** FLCAS, phát triển bởi Đại học Texas tại Austin, là một trong những công cụ quan trọng nhất để đo lường lo âu khi nói tiếng Anh.",

  // Support
  "support.title": "Hỗ trợ đúng kỹ năng bạn cần nhất",
  "support.notAlone": "Nếu bạn thấy kỹ năng nói khó, bạn không cô đơn.",
  "support.stat1Value": "7/10",
  "support.stat1Label": "học sinh cho biết Nói là kỹ năng yếu nhất",
  "support.stat2Value": "Lo âu là rào cản lớn nhất",
  "support.stat2Label": "sợ bị cười (95%), sợ sai (86%), thiếu tự tin (75%)",
  "support.stat3Value": "5.6–5.7",
  "support.stat3Label": "Nói là kỹ năng có điểm thấp nhất của thí sinh Việt Nam theo báo cáo IELTS gần đây",
  "support.systemProblem": "Không phải do bạn — mà do hệ thống",
  "support.systemIntro": "Nói là kỹ năng ít được dạy và thực hành nhất. Hơn",
  "support.systemPercent": "70%",
  "support.systemTeachers": "giáo viên tiếng Anh tại Việt Nam cho biết:",
  "support.issue1": "Sĩ số quá đông để cho học sinh thời gian luyện nói",
  "support.issue2": "Không đủ thời lượng trên lớp",
  "support.issue3": "Hoạt động nói cần nhiều chuẩn bị",
  "support.issue4": "Học sinh quá ngại hoặc quá lo lắng nếu không có hỗ trợ",

  // Solution
  "solution.title": "Lingriser Learning Loop",
  "solution.subtitle":
    "Phương pháp độc quyền, phối hợp 3 thành phần giúp bạn tăng tự tin, giao tiếp lưu loát và chuẩn bị sẵn sàng cho các kỳ thi.",
  "solution.learnTitle": "Xây nền tảng vững chắc",
  "solution.learnDesc": "Học trên lớp với giáo viên để được hướng dẫn cặn kẽ những nội dung khó tự luyện",
  "solution.loopTitle": "Tự luyện hàng ngày với AI",
  "solution.loopDesc": "Luyện nói thoải mái, không ngại ngùng, và được AI sửa sai lập tức mọi lúc mọi nơi",
  "solution.levelUpTitle": "Nâng tầm với mentor bản xứ",
  "solution.levelUpDesc":
    "Trò chuyện trực tuyến với mentor bản xứ để tăng phản xạ, phát âm, tâm lý tự tin cho các kỳ thi.",

  // Features
  "features.title": "Điểm khác biệt của Lingriser",
  "features.subtitle": "Phương pháp đột phá kết hợp công nghệ AI tiên tiến với chuyên môn của con người",
  "features.curriculum": "Giáo trình sát đề thi",
  "features.curriculumDesc":
    "Bài học chuẩn CEFR, tâp trung các kỹ năng mục tiêu cần thiết để thành công trong kỳ thi thực tế.",
  "features.aiPractice": "Luyện nói cùng AI",
  "features.aiPracticeDesc":
    "Luyện nói không áp lực hay ngại sai với AI mọi lúc mọi nơi, để tăng cường sự tự tin và độ lưu loát.",
  "features.mentor": "Mentor bản xứ",
  "features.mentorDesc": "Học trực tuyến 1-1 với người bản xứ chi phí hợp lý để luyện phát âm và phản xạ tự nhiên",
  "features.riseMeter": "Tiến bộ với Rise Meter™",
  "features.riseMeterDesc":
    "Công cụ theo dõi tiến trình học tập đột phá, giúp bạn liên tục tiến bộ và nâng cao điểm số.",
  "features.personalized": "Lộ trình học cá nhân hóa",
  "features.personalizedDesc":
    "Các bài luyện tập được điều chỉnh linh hoạt theo nhu cầu và tiến độ để đạt kết quả nhanh và tối ưu hơn.",

  // Why It Works
  "why.title": "Tại Sao Phương Pháp Này Hiệu Quả",
  "why.subtitle":
    "Dựa trên nghiên cứu hàng đầu từ Đại học Iowa State, Texas A&M, Đại học Hawai'i và University College London, Lingriser kết hợp các yếu tố đã được chứng minh giúp cải thiện kỹ năng nói:",
  "why.aiTitle": "Luyện Tập Với AI",
  "why.aiDesc": "Phản hồi tức thì giúp tăng cường phát âm, độ lưu loát và độ chính xác.",
  "why.mentorTitle": "Hội Thoại Với Mentor Bản Xứ",
  "why.mentorDesc":
    "Tương tác với người nói thành thạo giúp xây dựng phản xạ tự nhiên, sự tự tin và kỹ năng giao tiếp thực tế.",
  "why.loopTitle": "Vòng Lặp Luyện Tập Giảm Lo Lắng",
  "why.loopDesc":
    "Các buổi AI áp lực thấp kết hợp với tương tác mentor hỗ trợ giúp giảm lo lắng khi nói và tăng tốc sự tự tin.",

  // How It Works
  "how.title": "Cách Thức Hoạt Động",
  "how.subtitle": "Hành trình từ lo lắng đến tự tin trong 6 bước đơn giản",
  "how.step1": "Đăng Ký",
  "how.step1Desc": "Đặt mục tiêu, trình độ và sở thích của bạn",
  "how.step2": "Làm Bài Đánh Giá Đầu Vào",
  "how.step2Desc": "Xác định điểm mạnh/yếu và mức độ tự tin.",
  "how.step3": "Tham Gia Lớp Học Hàng Tuần",
  "how.step3Desc": "Xây dựng nền tảng với giáo viên trên lớp",
  "how.step4": "Luyện Tập Hàng Ngày với AI",
  "how.step4Desc": "Tăng độ lưu loát và tự tin.",
  "how.step5": "Giao tiếp với Mentor bản xứ",
  "how.step5Desc": "Nâng cao phản xạ giao tiếp",
  "how.step6": "Theo Dõi Tiến Trình với Rise Meter™",
  "how.step6Desc": "Cập nhật tiến bộ liên tục mỗi tuần.",

  // Pricing
  "pricing.title": "Học Phí Thông Minh",
  "pricing.subtitle": "Các gói học phí linh hoạt, phù hợp với mọi nhu cầu và khả năng tài chính",
  "pricing.cohort": "Theo Khoá",
  "pricing.flexible": "Theo Nhu Cầu",
  "pricing.6weeks": "6 Tuần",
  "pricing.8weeks": "8 Tuần",
  "pricing.12weeks": "12 Tuần",
  "pricing.bestValue": "Giá Trị Tốt Nhất",
  "pricing.mostSavings": "Tiết Kiệm Nhất",
  "pricing.maxResults": "Kết Quả Tối Đa",
  "pricing.weeklyClass": "1 buổi học trên lớp mỗi tuần",
  "pricing.limitedAI": "3 buổi luyện tập AI mỗi tuần",
  "pricing.unlimitedAI": "Luyện tập AI không giới hạn",
  "pricing.weeklyMentor45": "1 buổi mentor 45 phút mỗi tuần",
  "pricing.weeklyMentor45x2": "2 buổi mentor 45 phút mỗi tuần",
  "pricing.riseMeterTracking": "Theo dõi tiến trình Rise Meter™",
  "pricing.cefrCurriculum": "Giáo trình chuẩn CEFR",
  "pricing.signUp": "Đăng Ký Ngay",
  "pricing.aiOnly": "Chỉ Luyện Tập AI",
  "pricing.aiOnlyDesc": "Hoàn hảo cho người tự học",
  "pricing.mentorOnly": "Chỉ Mentor",
  "pricing.mentorOnlyDesc": "Buổi học mentor một lần",
  "pricing.combo": "AI + Mentor Kết Hợp",
  "pricing.comboDesc": "Tốt nhất của cả hai",
  "pricing.unlimitedAIPractice": "Luyện nói AI không giới hạn",
  "pricing.realTimeFeedback": "Phản hồi theo thời gian thực",
  "pricing.progressTracking": "Theo dõi tiến trình",
  "pricing.30minSession": "Buổi học 1-1 30 phút",
  "pricing.nativeMentor": "Mentor người bản xứ",
  "pricing.personalizedFeedback": "Phản hồi cá nhân hóa",
  "pricing.4sessions": "4 buổi mentor mỗi tháng",
  "pricing.fullTracking": "Theo dõi tiến trình đầy đủ",
  "pricing.start": "Bắt Đầu",

  // FAQ
  "faq.title": "Câu Hỏi Thường Gặp",
  "faq.subtitle": "Tất cả những gì bạn cần biết về Lingriser",
  "faq.q1": "Chương trình bao gồm những gì?",
  "faq.a1":
    "Chương trình đầy đủ bao gồm các buổi học hàng tuần với giáo viên, luyện nói với AI không giới hạn, các buổi huấn luyện với mentor hàng tuần, và quyền truy cập hệ thống theo dõi tiến trình Rise Meter™. Tất cả đều theo chuẩn CEFR và được thiết kế để xây dựng sự tự tin khi nói.",
  "faq.q2": "Giáo viên và mentor là ai?",
  "faq.a2":
    "Giáo viên của chúng tôi là những nhà giáo dục tiếng Anh có chứng chỉ với kinh nghiệm giảng dạy tại Việt Nam. Các mentor là người bản xứ nói tiếng Anh hoặc những người nói tiếng Anh trình độ cao đã được đào tạo để cung cấp phản hồi hỗ trợ và mang tính xây dựng.",
  "faq.q3": "Làm thế nào để đăng ký và thanh toán?",
  "faq.a3":
    "Đăng ký rất đơn giản qua website của chúng tôi. Chúng tôi chấp nhận chuyển khoản ngân hàng, thẻ tín dụng và các phương thức thanh toán phổ biến tại Việt Nam.",
  "faq.q4": "Chương trình giúp gì cho việc khắc phục lo lắng và phát triển kỹ năng nói?",
  "faq.a4":
    "Chúng tôi sử dụng phương pháp dựa trên nghiên cứu kết hợp luyện tập AI áp lực thấp (hoàn hảo cho người học lo lắng), các bài học có cấu trúc trên lớp, và huấn luyện mentor hỗ trợ.",
  "faq.q5": "Học sinh theo dõi tiến trình như thế nào?",
  "faq.a5":
    "Hệ thống Rise Meter™ của chúng tôi cung cấp cập nhật hàng tuần về độ lưu loát, mức độ tự tin và sự sẵn sàng cho kỳ thi.",
  "faq.q6": "Chương trình phù hợp với độ tuổi hoặc trình độ nào?",
  "faq.a6": "Chương trình được thiết kế cho học sinh lớp 6–12 với trình độ CEFR A2–B1.",
  "faq.q7": "Tôi có thể thử các buổi AI hoặc mentor mà không cần tham gia khóa học không?",
  "faq.a7": "Có! Chúng tôi cung cấp các tùy chọn thanh toán linh hoạt theo nhu cầu.",
  "faq.q8": "Chương trình có quá nặng không? Tôi không muốn con bị áp lực.",
  "faq.a8": "Không hề! Đây không phải chương trình truyền thống nặng về ngữ pháp và nhàm chán. Lingriser tập trung tạo môi trường tương tác, thực hành để học sinh tự nhiên đắm mình trong môi trường nói tiếng Anh, phát triển phản xạ ngôn ngữ và sử dụng tiếng Anh tự nhiên trong các bối cảnh và tình huống thực tế thông qua các phương pháp học tập chủ động như đóng vai, luyện tập theo cặp, và nhiều hoạt động khác.",
  "faq.q9": "Con tôi có còn học ngữ pháp, từ vựng, đọc, nghe như bình thường không?",
  "faq.a9": "Có! Mặc dù chương trình tập trung vào kỹ năng nói, học sinh vẫn học ngữ pháp, từ vựng, đọc và nghe như những kỹ năng hỗ trợ để phát triển khả năng giao tiếp. Chương trình Lingriser được thiết kế để bổ sung, không phải thay thế chương trình tiếng Anh truyền thống ở trường.",

  // CTA
  "cta.limited": "Số lượng có hạn cho khóa học tiếp theo",
  "cta.title": "Bắt Đầu Hành Trình Cùng Chúng Tôi",
  "cta.subtitle": "Sẵn sàng xây dựng sự tự tin và kết quả nói thực sự?",
  "cta.startNow": "Bắt Đầu Ngay",
  "cta.bookConsult": "Đặt Lịch Tư Vấn",
  "cta.noCard": "✓ Không cần thẻ tín dụng • ✓ Tư vấn miễn phí",

  // Booking Demo
  "booking.title": "Đặt Lịch với Mentor",
  "booking.subtitle": "Chọn mentor phù hợp và đặt lịch học 1-1 để cải thiện kỹ năng giao tiếp tiếng Anh",
  "booking.step1": "Chọn Mentor",
  "booking.step2": "Chọn Thời Gian",
  "booking.step3": "Xác Nhận",
  "booking.selectMentor": "Chọn Mentor",
  "booking.reviews": "đánh giá",
  "booking.back": "Quay lại",
  "booking.timeSlots": "Khung giờ",
  "booking.selectDate": "Chọn ngày để xem khung giờ",
  "booking.confirmTime": "Xác nhận thời gian",
  "booking.pleaseSelectDate": "Vui lòng chọn ngày trên lịch",
  "booking.backToTime": "Quay lại chọn thời gian",
  "booking.confirmBooking": "Xác nhận đặt lịch",
  "booking.reviewInfo": "Vui lòng kiểm tra thông tin trước khi xác nhận",
  "booking.mentor": "Mentor",
  "booking.date": "Ngày",
  "booking.time": "Giờ",
  "booking.sessionType": "Hình thức học:",
  "booking.videoCall": "Học với GV nước ngoài",
  "booking.voiceCall": "Voice call",
  "booking.mentorSpecialties": "Chuyên môn của mentor:",
  "booking.confirmBtn": "Xác nhận đặt lịch",
  "booking.demoNote": "* Đây là trang demo. Trong thực tế, bạn sẽ nhận được email xác nhận.",
  "booking.success": "Đặt lịch thành công!",
  "booking.successMsg": "Bạn đã đặt lịch học với",
  "booking.at": "vào",
  "booking.nextSteps": "Bước tiếp theo:",
  "booking.nextStep1": "Kiểm tra email để nhận link tham gia buổi học",
  "booking.nextStep2": "Chuẩn bị tai nghe và micro để có trải nghiệm tốt nhất",
  "booking.nextStep3": "Tham gia đúng giờ để tận dụng tối đa thời gian học",
  "booking.bookAnother": "Đặt lịch khác",
  "booking.goHome": "Về trang chủ",

  // AI Practice Demo
  "aiPractice.badge": "Luyện Tập với AI",
  "aiPractice.title": "Trải Nghiệm Luyện Nói với AI",
  "aiPractice.subtitle": "Thử nghiệm hệ thống AI thông minh giúp bạn luyện nói tiếng Anh và nhận phản hồi chi tiết",
  "aiPractice.step1": "Chọn Loại",
  "aiPractice.step2": "Chọn Chủ Đề",
  "aiPractice.step3": "Chọn Cấp Độ",
  "aiPractice.step4": "Chọn Chế Độ",
  "aiPractice.step5": "Luyện Tập",
  "aiPractice.step6": "Phản Hồi",
  "aiPractice.back": "Quay lại",
  "aiPractice.ieltsTitle": "IELTS Speaking",
  "aiPractice.ieltsDesc": "Luyện tập các phần thi IELTS Speaking với AI đóng vai giám khảo",
  "aiPractice.ieltsPart1": "Part 1: Câu hỏi cá nhân",
  "aiPractice.ieltsPart2": "Part 2: Cue Card",
  "aiPractice.ieltsPart3": "Part 3: Thảo luận chuyên sâu",
  "aiPractice.conversationTitle": "Hội Thoại Hằng Ngày",
  "aiPractice.conversationDesc": "Thực hành giao tiếp trong các tình huống thực tế với AI",
  "aiPractice.conv1": "Gọi món ăn",
  "aiPractice.conv2": "Kết bạn mới",
  "aiPractice.conv3": "Phỏng vấn xin việc",
  "aiPractice.selectIelts": "Chọn Phần Thi IELTS Speaking",
  "aiPractice.selectConv": "Chọn Chủ Đề Hội Thoại",
  "aiPractice.selectIeltsHint": "Lựa chọn phần thi bạn muốn luyện tập",
  "aiPractice.selectConvHint": "Chọn tình huống bạn muốn thực hành",
  "aiPractice.inputPlaceholder": "Nhập câu trả lời hoặc nhấn mic để nói...",
  "aiPractice.demoHint": "💡 Đây là bản demo - trong phiên bản đầy đủ, AI sẽ phân tích giọng nói thực của bạn",
  "aiPractice.overallScore": "Điểm Tổng Thể",
  "aiPractice.outOf9": "trên thang điểm 9.0",
  "aiPractice.detailedAnalysis": "Phân Tích Chi Tiết",
  "aiPractice.pronunciation": "Phát âm",
  "aiPractice.grammar": "Ngữ pháp",
  "aiPractice.vocabulary": "Từ vựng",
  "aiPractice.fluency": "Lưu loát",
  "aiPractice.coherence": "Mạch lạc",
  "aiPractice.strengths": "Điểm Mạnh",
  "aiPractice.suggestions": "Gợi Ý Cải Thiện",
  "aiPractice.tryAgain": "Thử Lại Chủ Đề Này",
  "aiPractice.newTopic": "Chọn Chủ Đề Mới",
  "aiPractice.selectLevel": "Chọn Cấp Độ Của Bạn",
  "aiPractice.selectLevelHint": "AI sẽ điều chỉnh độ khó phù hợp với trình độ của bạn",
  "aiPractice.level.beginner": "Người Mới Bắt Đầu",
  "aiPractice.level.beginnerDesc": "CEFR A1-A2 • Từ vựng đơn giản, câu ngắn",
  "aiPractice.level.beginnerFeature1": "Từ vựng cơ bản",
  "aiPractice.level.beginnerFeature2": "Nói chậm và rõ ràng",
  "aiPractice.level.beginnerFeature3": "Nhiều gợi ý hỗ trợ",
  "aiPractice.level.intermediate": "Trung Cấp",
  "aiPractice.level.intermediateDesc": "CEFR B1-B2 • Hội thoại tự nhiên",
  "aiPractice.level.intermediateFeature1": "Câu phức tạp hơn",
  "aiPractice.level.intermediateFeature2": "Sửa lỗi nhẹ nhàng",
  "aiPractice.level.intermediateFeature3": "Khuyến khích mở rộng",
  "aiPractice.level.advanced": "Nâng Cao",
  "aiPractice.level.advancedDesc": "CEFR C1-C2 • Thảo luận chuyên sâu",
  "aiPractice.level.advancedFeature1": "Từ vựng phong phú",
  "aiPractice.level.advancedFeature2": "Thành ngữ và cấu trúc phức tạp",
  "aiPractice.level.advancedFeature3": "Thách thức tư duy",
  "aiPractice.selectMode": "Chọn Chế Độ Luyện Tập",
  "aiPractice.selectModeHint": "Bạn muốn luyện nói bằng giọng nói hay chat?",
  "aiPractice.mode.voice": "Chế Độ Giọng Nói",
  "aiPractice.mode.voiceDesc": "Trò chuyện tự nhiên với AI bằng giọng nói của bạn",
  "aiPractice.mode.voiceFeature1": "Nói chuyện như thật",
  "aiPractice.mode.voiceFeature2": "Phụ đề hỗ trợ",
  "aiPractice.mode.voiceFeature3": "Gợi ý câu trả lời",
  "aiPractice.mode.chat": "Chế Độ Chat",
  "aiPractice.mode.chatDesc": "Nhập câu trả lời và nhận phản hồi chi tiết",
  "aiPractice.mode.chatFeature1": "Thời gian suy nghĩ",
  "aiPractice.mode.chatFeature2": "Xem lại hội thoại",
  "aiPractice.mode.chatFeature3": "Gợi ý câu trả lời",
  "aiPractice.suggestedResponses": "Gợi ý câu trả lời:",
  "aiPractice.voice.title": "Luyện Nói với AI",
  "aiPractice.voice.connected": "Đã kết nối!",
  "aiPractice.voice.error": "Lỗi kết nối",
  "aiPractice.voice.captions": "Phụ đề",
  "aiPractice.voice.aiSpeaking": "AI đang nói...",
  "aiPractice.voice.yourTurn": "Đến lượt bạn!",
  "aiPractice.voice.listenCarefully": "Hãy lắng nghe cẩn thận",
  "aiPractice.voice.speakNow": "Hãy nói câu trả lời của bạn",
  "aiPractice.voice.ready": "Sẵn sàng bắt đầu",
  "aiPractice.voice.clickToStart": "Nhấn nút bên dưới để bắt đầu",
  "aiPractice.voice.connecting": "Đang kết nối...",
  "aiPractice.voice.startCall": "Bắt đầu",
  "aiPractice.voice.endCall": "Kết thúc",
  "aiPractice.voice.hint": "Nói rõ ràng và tự nhiên. AI sẽ lắng nghe và phản hồi.",
  "aiPractice.voice.finish": "Hoàn thành và xem phản hồi",
  "aiPractice.voice.setupRequired": "Cần cấu hình ElevenLabs Agent",
  "aiPractice.voice.setupHint": "Nhập Agent ID từ ElevenLabs để sử dụng chế độ giọng nói",
  "aiPractice.voice.agentIdPlaceholder": "Nhập ElevenLabs Agent ID",
  "aiPractice.voice.continue": "Tiếp tục",
  "aiPractice.voice.createAgentHint": "Tạo agent tại elevenlabs.io/conversational-ai",
  "aiPractice.voice.noAgentId": "Vui lòng nhập Agent ID",
  "aiPractice.voice.connectionFailed": "Không thể kết nối. Vui lòng thử lại.",
  "aiPractice.chat.title": "Chat Luyện Tập",
  "aiPractice.chat.hint": "Nhập câu trả lời hoặc chọn gợi ý bên trên",
  "aiPractice.chat.finish": "Hoàn thành",
  "aiPractice.rateLimited": "Quá nhiều yêu cầu. Vui lòng thử lại sau.",
  "aiPractice.paymentRequired": "Cần nạp thêm credits để tiếp tục.",
  "aiPractice.connectionError": "Lỗi kết nối. Vui lòng thử lại.",
  "aiPractice.endPractice": "Kết thúc luyện tập",
  "aiPractice.analyzingPerformance": "Đang phân tích kết quả...",
  "aiPractice.pleaseWait": "Vui lòng đợi trong giây lát khi AI đánh giá bài nói của bạn",
  "aiPractice.feedbackError": "Không thể tạo phản hồi. Đang hiển thị kết quả mặc định.",

  // Common
  "common.month1": "Tháng 1",
  "common.month2": "Tháng 2",
  "common.month3": "Tháng 3",
  "common.month4": "Tháng 4",
  "common.month5": "Tháng 5",
  "common.month6": "Tháng 6",
  "common.month7": "Tháng 7",
  "common.month8": "Tháng 8",
  "common.month9": "Tháng 9",
  "common.month10": "Tháng 10",
  "common.month11": "Tháng 11",
  "common.month12": "Tháng 12",
  "common.sun": "CN",
  "common.mon": "T2",
  "common.tue": "T3",
  "common.wed": "T4",
  "common.thu": "T5",
  "common.fri": "T6",
  "common.sat": "T7",
  "common.sunday": "Chủ nhật",
  "common.monday": "Thứ hai",
  "common.tuesday": "Thứ ba",
  "common.wednesday": "Thứ tư",
  "common.thursday": "Thứ năm",
  "common.friday": "Thứ sáu",
  "common.saturday": "Thứ bảy",

  // Parent Dashboard
  "parent.badge": "Dành Cho Phụ Huynh",
  "parent.title": "Theo Dõi Tiến Trình Học Của Con",
  "parent.subtitle": "Xem tổng quan về tiến độ học tập, điểm danh và thành tích của con bạn",
  "parent.selectChild": "Chọn con để xem",
  "parent.progressVideos": "Video Tiến Bộ",
  "parent.beforeVideo": "Trước Khóa Học",
  "parent.afterVideo": "Sau Khóa Học",
  "parent.entryTestRecording": "Bài kiểm tra đầu vào",
  "parent.graduationRecording": "Bài tốt nghiệp",
  "parent.beforeVideoDesc": "Video ghi lại bài nói của học sinh trong bài kiểm tra đầu vào trước khi bắt đầu chương trình.",
  "parent.afterVideoDesc": "Video ghi lại bài nói của học sinh khi hoàn thành chương trình.",
  "parent.demoNote": "Đây là trang demo. Dữ liệu được hiển thị là mẫu minh họa.",

  // Inaugural Program
  "inaugural.badge": "Chương Trình Khai Giảng",
  "inaugural.title": "Chương Trình Nền Tảng Giao Tiếp",
  "inaugural.subtitle": "Khóa học 8 tuần được thiết kế để xây dựng nền tảng nói tiếng Anh vững chắc thông qua phương pháp học kết hợp độc đáo.",
  "inaugural.overviewTitle": "Tổng Quan Chương Trình",
  "inaugural.programLength": "Thời lượng",
  "inaugural.programLengthValue": "8 tuần",
  "inaugural.programFormat": "Hình thức học",
  "inaugural.programFormatValue": "Học kết hợp (Học với GV Việt Nam + Luyện nói AI hàng ngày + Học 1-1 với GV nước ngoài hàng tuần)",
  "inaugural.targetLevel": "Trình độ mục tiêu",
  "inaugural.targetLevelValue": "CEFR A2–B1 (Học sinh làm bài kiểm tra đầu vào ngắn để đảm bảo xếp lớp phù hợp)",
  "inaugural.classSize": "Sĩ số lớp",
  "inaugural.classSizeValue": "15 học sinh/lớp (1 giáo viên/nhóm để tối đa thời gian nói)",
  "inaugural.mentorPractice": "Luyện tập với Mentor",
  "inaugural.mentorPracticeValue": "Buổi học 1-1 hàng tuần với mentor bản xứ",
  "inaugural.aiPractice": "Luyện nói với AI",
  "inaugural.aiPracticeValue": "Truy cập không giới hạn, luyện tập mọi lúc trong suốt chương trình",

  "inaugural.weeklyScheduleTitle": "Lịch Học Hàng Tuần",
  "inaugural.weeklyScheduleDesc": "Mỗi tuần theo một nhịp học nhất quán và có chủ đích, giúp học sinh chuyển từ chuẩn bị → luyện tập → giao tiếp thực tế.",

  "inaugural.step1Title": "Học Với Giáo Viên Việt Nam",
  "inaugural.step1Timing": "Đầu tuần",
  "inaugural.step1Intro": "Tuần bắt đầu với buổi học với giáo viên Việt Nam, nơi học sinh được giới thiệu trọng tâm nói và các kỹ năng giao tiếp cốt lõi trong tuần.",
  "inaugural.studentsWill": "Trong buổi học, học sinh sẽ:",
  "inaugural.step1Point1": "Tìm hiểu chủ đề và mục tiêu nói trong tuần",
  "inaugural.step1Point2": "Luyện nói thông qua các hoạt động có hướng dẫn và tương tác nhóm nhỏ",
  "inaugural.step1Point3": "Nhận hỗ trợ ngôn ngữ (từ vựng, cấu trúc câu, chiến lược nói)",
  "inaugural.step1Point4": "Xây dựng sự tự tin trong môi trường hỗ trợ, ít áp lực",
  "inaugural.step1Footer": "Buổi học này tạo nền tảng cho tất cả các hoạt động luyện tập trong tuần.",

  "inaugural.step2Title": "Luyện Nói AI Hàng Ngày",
  "inaugural.step2Timing": "Trong tuần, tại nhà",
  "inaugural.step2Intro": "Sau buổi học trên lớp, học sinh luyện nói tại nhà với công cụ AI, truy cập không giới hạn trong suốt tuần.",
  "inaugural.aiAllows": "Luyện tập AI giúp học sinh:",
  "inaugural.step2Point1": "Ôn luyện những gì đã học trên lớp theo tốc độ riêng",
  "inaugural.step2Point2": "Luyện phát âm, độ lưu loát và cấu trúc câu",
  "inaugural.step2Point3": "Lặp lại bài tập nói nhiều lần tùy ý mà không áp lực",
  "inaugural.step2Point4": "Xây dựng sự tự tin trước khi nói với người khác",
  "inaugural.step2Footer": "Các buổi luyện tập ngắn, thường xuyên giúp học sinh hình thành thói quen nói và giảm lo lắng theo thời gian.",

  "inaugural.step3Title": "Buổi Học 1-1 Với Mentor",
  "inaugural.step3Timing": "Cuối tuần",
  "inaugural.step3Intro": "Cuối tuần—thường là Thứ Sáu hoặc cuối tuần—học sinh tham gia buổi học trực tuyến 1-1 với mentor bản xứ.",
  "inaugural.step3Point1": "Áp dụng những gì đã luyện tập trong tuần vào cuộc hội thoại thực",
  "inaugural.step3Point2": "Nói chuyện với người nghe mới nhưng thân thiện",
  "inaugural.step3Point3": "Tiếp xúc với cách sử dụng tiếng Anh tự nhiên và các giọng nói khác nhau",
  "inaugural.step3Point4": "Xây dựng sự tự tin chuyển đổi luyện tập thành giao tiếp thực",
  "inaugural.step3Footer": "Buổi học với mentor giúp học sinh \"nâng tầm\" bằng cách kết nối việc học trên lớp và luyện tập AI với tương tác thực tế.",

  "inaugural.sampleWeekTitle": "Lịch Trình Mẫu — Tuần 1",
  "inaugural.week1Focus": "Trọng Tâm Tuần 1",
  "inaugural.week1Theme": "Chủ đề: Bản thân & thế giới hàng ngày",
  "inaugural.week1Goal": "Mục tiêu nói: Học sinh tự giới thiệu ngắn gọn, có chuẩn bị mà không né tránh việc nói.",

  "inaugural.mondayTitle": "Thứ Hai",
  "inaugural.mondaySubtitle": "Buổi Học Với Giáo Viên Việt Nam",
  "inaugural.mondayFormat": "Hình thức: Lớp nhóm nhỏ (15 học sinh, 1 giáo viên)",
  "inaugural.learnPractice": "Học sinh học và luyện tập:",
  "inaugural.mondayPoint1": "Kỳ vọng và quy tắc rõ ràng: Sai lầm là điều bình thường và là một phần của việc học",
  "inaugural.mondayPoint2": "Tự giới thiệu có hướng dẫn sử dụng khung câu (ví dụ: \"Mình là...\", \"Mình thường...\", \"Mình thích...\")",
  "inaugural.mondayPoint3": "Nói theo cặp và nhóm nhỏ với thời gian chuẩn bị",
  "inaugural.mondayPoint4": "Giáo viên làm mẫu: cách dừng tự nhiên, cách do dự và tiếp tục nói, cách phục hồi khi không chắc chắn",
  "inaugural.competencyFocus": "Trọng tâm năng lực (Tuần 1):",
  "inaugural.competency1": "Nói: Tự giới thiệu có hỗ trợ",
  "inaugural.competency2": "Nghe để nói: Nghe các đoạn quen thuộc (tên, thói quen, sở thích)",
  "inaugural.competency3": "Tài nguyên ngôn ngữ: Từ vựng cá nhân tần suất cao; khung thì hiện tại đơn",
  "inaugural.competency4": "Phát âm & rõ ràng: Trọng âm từ; nói chậm hơn để rõ ràng",
  "inaugural.competency5": "Tự tin & chiến lược: Sử dụng từ đệm (\"để mình nghĩ\"), chấp nhận im lặng mà không dừng lại",

  "inaugural.tueThuTitle": "Thứ Ba–Thứ Năm",
  "inaugural.tueThuSubtitle": "Luyện Nói AI Hàng Ngày",
  "inaugural.tueThuFormat": "Hình thức: Buổi luyện tập ngắn hàng ngày (10–15 phút mỗi buổi) | Truy cập: Không giới hạn trong tuần",
  "inaugural.studentsDo": "Học sinh làm gì:",
  "inaugural.tueThuPoint1": "Luyện tự giới thiệu với các gợi ý AI ít áp lực",
  "inaugural.tueThuPoint2": "Lặp lại bài tập nói nhiều lần tùy ý",
  "inaugural.tueThuPoint3": "Xem trước và ôn lại từ vựng chính để sử dụng trên lớp",
  "inaugural.tueThuPoint4": "Luyện nói mà không sợ bị đánh giá",
  "inaugural.aiProvides": "AI cung cấp gì:",
  "inaugural.aiFeedbackDesc": "Phản hồi trung lập về nội dung, tập trung vào: hoàn thành, độ dài, rõ ràng (không phải độ chính xác ngữ pháp)",
  "inaugural.aiPurpose": "Mục đích của AI tuần này: Giúp học sinh ôn luyện nói an toàn và xây dựng sự thoải mái trước khi nói với người thật.",

  "inaugural.fridayTitle": "Thứ Sáu hoặc Cuối Tuần",
  "inaugural.fridaySubtitle": "Buổi Học 1-1 Với Mentor",
  "inaugural.fridayFormat": "Hình thức: Buổi học cá nhân với mentor bản xứ",
  "inaugural.inSession": "Trong buổi học:",
  "inaugural.fridayPoint1": "Xây dựng mối quan hệ qua hội thoại dựa trên chủ đề Tuần 1",
  "inaugural.fridayPoint2": "Học sinh tự giới thiệu và nói về cuộc sống hàng ngày",
  "inaugural.fridayPoint3": "Mentor phản ánh tích cực ngôn ngữ của học sinh",
  "inaugural.fridayPoint4": "Tập trung vào sự thoải mái, rõ ràng và khuyến khích",
  "inaugural.mentorsDoNot": "Mentor KHÔNG làm:",
  "inaugural.mentorNoDoDesc": "Không kiểm tra, không sửa nặng, không áp lực",
  "inaugural.mentorPurpose": "Mục đích của buổi học với mentor: Giúp học sinh chuyển đổi luyện tập thành giao tiếp thực với người nghe thân thiện.",

  "inaugural.week1Evidence": "Bằng Chứng & Kết Quả Tuần 1",
  "inaugural.byEndOfWeek1": "Cuối Tuần 1:",
  "inaugural.evidence1": "Học sinh hoàn thành bản ghi âm nói cơ sở",
  "inaugural.evidence2": "Học sinh hoàn thành tự đánh giá sự tự tin (S-FLCAS trước)",
  "inaugural.evidence3": "Giáo viên và mentor xác lập điểm xuất phát rõ ràng cho tiến độ",
  "inaugural.evidenceNote": "Bằng chứng này được sử dụng để hỗ trợ việc học, không phải để đánh giá hiệu suất.",

  "inaugural.exclusiveBenefits": "Quyền Lợi Độc Quyền",
  "inaugural.benefitsTitle": "Quyền Lợi Khóa Khai Giảng",
  "inaugural.benefitsDesc": "Nhóm sắp tới sẽ là khóa khai giảng của chúng tôi—những học sinh đầu tiên trải nghiệm chương trình nền tảng nói đầy đủ của Lingriser.",
  "inaugural.benefit1Title": "Hỗ trợ học phí",
  "inaugural.benefit1Desc": "Dành cho chương trình này",
  "inaugural.8weekProgram": "Chương trình 8 tuần",
  "inaugural.benefit2Title": "Ưu đãi học phí trọn đời",
  "inaugural.benefit2Desc": "Cho các chương trình Lingriser trong tương lai",
  "inaugural.benefitsFooter": "Những quyền lợi này ghi nhận các gia đình đặt niềm tin vào Lingriser khi chúng tôi ra mắt lộ trình học tập hoàn chỉnh.",

  "inaugural.registerTitle": "Đăng Ký Quan Tâm (Không Ràng Buộc)",
  "inaugural.registerSubtitle": "Biểu mẫu này không phải là đăng ký nhập học và không yêu cầu thanh toán.",
  "inaugural.registerNote": "Đăng ký quan tâm cho phép chúng tôi:",
  "inaugural.registerBenefit1": "Chia sẻ thông tin chi tiết đầy đủ về chương trình",
  "inaugural.registerBenefit2": "Liên hệ với bạn khi mở đăng ký",
  "inaugural.registerBenefit3": "Giữ quyền lợi khóa khai giảng cho bạn",
  "inaugural.parentName": "Họ tên phụ huynh",
  "inaugural.parentNamePlaceholder": "Nhập họ tên",
  "inaugural.phone": "Số điện thoại",
  "inaugural.phonePlaceholder": "Nhập số điện thoại",
  "inaugural.email": "Email",
  "inaugural.emailPlaceholder": "Nhập địa chỉ email",
  "inaugural.submit": "Đăng Ký Quan Tâm",
  "inaugural.submitting": "Đang gửi...",
  "inaugural.contactNote": "Chúng tôi sẽ liên hệ với bạn trước khi chương trình bắt đầu.",
  "inaugural.formSuccess": "Đã đăng ký thành công! Chúng tôi sẽ liên hệ với bạn sớm.",
  "inaugural.formError": "Có lỗi xảy ra. Vui lòng thử lại.",
  "inaugural.pleaseSelectIntent": "Vui lòng cho biết bạn có muốn đăng ký không.",
  "inaugural.primaryGoalQuestion": "Mục tiêu chính của bạn khi chọn chương trình cho con là gì?",
  "inaugural.goalAcademic": "Cải thiện kết quả học tập (điểm số, bài kiểm tra)",
  "inaugural.goalConfidence": "Xây dựng sự tự tin khi nói tiếng Anh",
  
  "inaugural.wantsToSignupQuestion": "Bạn có muốn đăng ký chương trình Speaking Foundation không?",
  "inaugural.yesInterested": "Có, tôi muốn đăng ký",
  "inaugural.noNotInterested": "Không, tôi chưa muốn đăng ký lúc này",
  "inaugural.whatInterestedYou": "Điều gì khiến bạn quan tâm đến chương trình? (Tùy chọn)",
  "inaugural.interestReasonPlaceholder": "Chia sẻ điều gì thu hút bạn nhất về chương trình này...",
  "inaugural.whyNotInterested": "Bạn có thể chia sẻ lý do không? Điều này sẽ giúp chúng tôi cải thiện. (Tùy chọn)",
  "inaugural.rejectionReasonPlaceholder": "Ví dụ: giá cả, thời gian không phù hợp, cần thêm thông tin...",

  // Instructor Section
  "inaugural.instructorTitle": "Giảng Viên Chương Trình",
  "inaugural.instructorSubtitle": "Học cùng chuyên gia giàu kinh nghiệm trong giảng dạy tiếng Anh",
  "inaugural.instructorName": "Thầy Trần Quốc Khải",
  "inaugural.instructorRole": "Giảng viên - Chương trình Speaking Foundation",
  "inaugural.qualifications": "Bằng cấp & Chứng chỉ",
  "inaugural.qual1": "Thạc sĩ Giảng dạy Tiếng Anh (TEFL/TESOL) - Đại học Cần Thơ",
  "inaugural.experience": "Kinh Nghiệm Giảng Dạy",
  "inaugural.exp1": "Hơn 6 năm kinh nghiệm giảng dạy tiếng Anh giao tiếp với video phim ảnh",
  "inaugural.instructorQuote": "Tôi tin rằng mọi học sinh đều có thể tự tin giao tiếp tiếng Anh khi được hướng dẫn đúng phương pháp và môi trường học tập phù hợp.",

  // Real Results
  "results.title": "Xem Kết Quả Thực Tế",
  "results.subtitle": "So sánh kỹ năng nói tiếng Anh trước và sau chương trình",
  "results.before": "Trước Chương Trình",
  "results.after": "Sau Chương Trình",
  "results.entryTest": "Bài kiểm tra đầu vào",
  "results.graduation": "Bài tốt nghiệp",
  "results.demoNote": "Các video được dùng cho mục đích minh họa, không phải học sinh thực tế.",
  "results.play": "Phát",
  "results.pause": "Tạm dừng",
  "results.mute": "Tắt tiếng",
  "results.unmute": "Bật tiếng",
  "results.viewProgram": "Xem Chương Trình",
};

const en: Record<string, string> = {
  // Navigation
  "nav.home": "Home",
  "nav.program": "Programs",
  "nav.forStudents": "For Students",
  "nav.forParents": "For Parents",
  "nav.aiPractice": "AI Practice",
  "nav.booking": "Book a Mentor",
  "nav.parentDashboard": "Parent Dashboard",
  "nav.login": "Log In",
  "nav.register": "Sign Up",
  "nav.allPrograms": "All Programs",

  // Hero
  "hero.title": "Level Up English Speaking with",
  "hero.ai": "AI",
  "hero.and": "and",
  "hero.nativeMentor": "Native Mentors",
  "hero.subtitle": "A science-based, comprehensive solution to help you overcome fear and confidently communicate to achieve your dream scores.",
  "hero.cta": "Discover what's holding you back",
  "hero.painPoint1": "I'm afraid to speak because I might make mistakes",
  "hero.painPoint2": "I rarely get to practice speaking in class",
  "hero.painPoint3": "I always feel stressed when speaking English",

  // Evidence
  "evidence.title": "Trusted expertise, solid scientific foundation",
  "evidence.ivyLeague": "Built by experts from Ivy League universities – USA",
  "evidence.cefr": "Aligned with CEFR A2–B1* (equivalent to IELTS 3.0–5.0)**",
  "evidence.cefrNote1": "* CEFR is the international English proficiency standard used in curricula and exams like TOEFL, IELTS.",
  "evidence.cefrNote2": "** based on the Cambridge English conversion framework.",
  "evidence.flcas": "Based on the S-FLCAS scale***",
  "evidence.flcasNote": "*** FLCAS, developed by the University of Texas at Austin, is one of the most important tools for measuring foreign language speaking anxiety.",

  // Support
  "support.title": "Supporting the skill you need most",
  "support.notAlone": "If you find Speaking difficult, you are not alone.",
  "support.stat1Value": "7/10",
  "support.stat1Label": "students say Speaking is their weakest skill",
  "support.stat2Value": "Anxiety is the biggest barrier",
  "support.stat2Label": "fear of being laughed at (95%), fear of mistakes (86%), lack of confidence (75%)",
  "support.stat3Value": "5.6–5.7",
  "support.stat3Label": "Speaking is the lowest-scoring skill for Vietnamese test-takers in recent IELTS reports",
  "support.systemProblem": "It's not you — it's the system",
  "support.systemIntro": "Speaking is the least taught and practiced skill. Over",
  "support.systemPercent": "70%",
  "support.systemTeachers": "of English teachers in Vietnam report:",
  "support.issue1": "Class sizes too large for speaking practice time",
  "support.issue2": "Insufficient class time",
  "support.issue3": "Speaking activities require extensive preparation",
  "support.issue4": "Students are too shy or anxious without support",

  // Solution
  "solution.title": "Lingriser Learning Loop",
  "solution.subtitle": "A proprietary method combining 3 components to boost confidence, fluent communication, and exam readiness.",
  "solution.learnTitle": "Build a solid foundation",
  "solution.learnDesc": "Learn in class with a teacher for guided instruction on content that's hard to self-study",
  "solution.loopTitle": "Practice daily with AI",
  "solution.loopDesc": "Practice speaking freely, without embarrassment, with instant AI corrections anytime, anywhere",
  "solution.levelUpTitle": "Level up with native mentors",
  "solution.levelUpDesc": "Converse online with native mentors to sharpen reflexes, pronunciation, and confidence for exams.",

  // Features
  "features.title": "What makes Lingriser different",
  "features.subtitle": "A breakthrough method combining cutting-edge AI technology with human expertise",
  "features.curriculum": "Exam-aligned curriculum",
  "features.curriculumDesc": "CEFR-aligned lessons focusing on target skills needed for success in real exams.",
  "features.aiPractice": "Practice speaking with AI",
  "features.aiPracticeDesc": "Practice speaking without pressure or fear of mistakes with AI anytime, anywhere, to build confidence and fluency.",
  "features.mentor": "Native mentors",
  "features.mentorDesc": "Affordable 1-on-1 online sessions with native speakers for natural pronunciation and reflexes",
  "features.riseMeter": "Progress with Rise Meter™",
  "features.riseMeterDesc": "A breakthrough progress tracking tool to help you continuously improve and raise your scores.",
  "features.personalized": "Personalized learning path",
  "features.personalizedDesc": "Practice sessions flexibly adjusted to your needs and pace for faster, optimal results.",

  // Why It Works
  "why.title": "Why This Method Works",
  "why.subtitle": "Based on leading research from Iowa State University, Texas A&M, University of Hawai'i, and University College London, Lingriser combines proven elements that improve speaking skills:",
  "why.aiTitle": "AI Practice",
  "why.aiDesc": "Instant feedback enhances pronunciation, fluency, and accuracy.",
  "why.mentorTitle": "Conversations With Native Mentors",
  "why.mentorDesc": "Interacting with proficient speakers builds natural reflexes, confidence, and real communication skills.",
  "why.loopTitle": "Anxiety-Reducing Practice Loop",
  "why.loopDesc": "Low-pressure AI sessions combined with supportive mentor interactions reduce speaking anxiety and accelerate confidence.",

  // How It Works
  "how.title": "How It Works",
  "how.subtitle": "The journey from anxiety to confidence in 6 simple steps",
  "how.step1": "Sign Up",
  "how.step1Desc": "Set your goals, level, and preferences",
  "how.step2": "Take the Entry Assessment",
  "how.step2Desc": "Identify strengths/weaknesses and confidence level.",
  "how.step3": "Join Weekly Classes",
  "how.step3Desc": "Build your foundation with in-class teachers",
  "how.step4": "Practice Daily with AI",
  "how.step4Desc": "Increase fluency and confidence.",
  "how.step5": "Speak with Native Mentors",
  "how.step5Desc": "Enhance communication reflexes",
  "how.step6": "Track with Rise Meter™",
  "how.step6Desc": "Continuous weekly progress updates.",

  // Pricing
  "pricing.title": "Smart Pricing",
  "pricing.subtitle": "Flexible pricing plans to suit every need and budget",
  "pricing.cohort": "By Cohort",
  "pricing.flexible": "Flexible",
  "pricing.6weeks": "6 Weeks",
  "pricing.8weeks": "8 Weeks",
  "pricing.12weeks": "12 Weeks",
  "pricing.bestValue": "Best Value",
  "pricing.mostSavings": "Most Savings",
  "pricing.maxResults": "Maximum Results",
  "pricing.weeklyClass": "1 in-class session per week",
  "pricing.limitedAI": "3 AI practice sessions per week",
  "pricing.unlimitedAI": "Unlimited AI practice",
  "pricing.weeklyMentor45": "1 mentor session (45 min) per week",
  "pricing.weeklyMentor45x2": "2 mentor sessions (45 min) per week",
  "pricing.riseMeterTracking": "Rise Meter™ progress tracking",
  "pricing.cefrCurriculum": "CEFR-aligned curriculum",
  "pricing.signUp": "Sign Up Now",
  "pricing.aiOnly": "AI Practice Only",
  "pricing.aiOnlyDesc": "Perfect for self-learners",
  "pricing.mentorOnly": "Mentor Only",
  "pricing.mentorOnlyDesc": "One-time mentor sessions",
  "pricing.combo": "AI + Mentor Combo",
  "pricing.comboDesc": "Best of both worlds",
  "pricing.unlimitedAIPractice": "Unlimited AI speaking practice",
  "pricing.realTimeFeedback": "Real-time feedback",
  "pricing.progressTracking": "Progress tracking",
  "pricing.30minSession": "30-minute 1-on-1 session",
  "pricing.nativeMentor": "Native mentor",
  "pricing.personalizedFeedback": "Personalized feedback",
  "pricing.4sessions": "4 mentor sessions per month",
  "pricing.fullTracking": "Full progress tracking",
  "pricing.start": "Get Started",

  // FAQ
  "faq.title": "Frequently Asked Questions",
  "faq.subtitle": "Everything you need to know about Lingriser",
  "faq.q1": "What does the program include?",
  "faq.a1": "The full program includes weekly in-class sessions, unlimited AI speaking practice, weekly mentor coaching sessions, and access to the Rise Meter™ progress tracking system. Everything is CEFR-aligned and designed to build speaking confidence.",
  "faq.q2": "Who are the teachers and mentors?",
  "faq.a2": "Our teachers are certified English educators with experience teaching in Vietnam. Mentors are native English speakers or highly proficient speakers trained to provide supportive, constructive feedback.",
  "faq.q3": "How do I register and pay?",
  "faq.a3": "Registration is simple through our website. We accept bank transfers, credit cards, and popular payment methods in Vietnam.",
  "faq.q4": "How does the program help with anxiety and speaking development?",
  "faq.a4": "We use a research-based method combining low-pressure AI practice (perfect for anxious learners), structured in-class lessons, and supportive mentor coaching.",
  "faq.q5": "How do students track progress?",
  "faq.a5": "Our Rise Meter™ system provides weekly updates on fluency, confidence level, and exam readiness.",
  "faq.q6": "What age or level is the program suitable for?",
  "faq.a6": "The program is designed for grade 6–12 students at CEFR A2–B1 level.",
  "faq.q7": "Can I try AI or mentor sessions without joining a course?",
  "faq.a7": "Yes! We offer flexible pay-as-you-go options.",
  "faq.q8": "Is the program too intense? I don't want my child to feel pressured.",
  "faq.a8": "Not at all! This is not a traditional grammar-heavy, boring program. Lingriser focuses on creating an interactive practice environment where students naturally immerse themselves in English speaking, developing language reflexes through active methods like role-playing, pair practice, and more.",
  "faq.q9": "Will my child still learn grammar, vocabulary, reading, and listening?",
  "faq.a9": "Yes! While the program focuses on speaking skills, students still learn grammar, vocabulary, reading, and listening as supporting skills. Lingriser is designed to complement, not replace, traditional school English programs.",

  // CTA
  "cta.limited": "Limited spots for the next cohort",
  "cta.title": "Start Your Journey With Us",
  "cta.subtitle": "Ready to build real confidence and speaking results?",
  "cta.startNow": "Get Started",
  "cta.bookConsult": "Book a Consultation",
  "cta.noCard": "✓ No credit card required • ✓ Free consultation",

  // Booking Demo
  "booking.title": "Book a Mentor",
  "booking.subtitle": "Choose a suitable mentor and book a 1-on-1 session to improve your English communication skills",
  "booking.step1": "Choose Mentor",
  "booking.step2": "Choose Time",
  "booking.step3": "Confirm",
  "booking.selectMentor": "Select Mentor",
  "booking.reviews": "reviews",
  "booking.back": "Back",
  "booking.timeSlots": "Time Slots",
  "booking.selectDate": "Select a date to view time slots",
  "booking.confirmTime": "Confirm time",
  "booking.pleaseSelectDate": "Please select a date on the calendar",
  "booking.backToTime": "Back to time selection",
  "booking.confirmBooking": "Confirm Booking",
  "booking.reviewInfo": "Please review the information before confirming",
  "booking.mentor": "Mentor",
  "booking.date": "Date",
  "booking.time": "Time",
  "booking.sessionType": "Session type:",
  "booking.videoCall": "Lesson with foreign teacher",
  "booking.voiceCall": "Voice call",
  "booking.mentorSpecialties": "Mentor specialties:",
  "booking.confirmBtn": "Confirm Booking",
  "booking.demoNote": "* This is a demo page. In practice, you will receive a confirmation email.",
  "booking.success": "Booking successful!",
  "booking.successMsg": "You have booked a session with",
  "booking.at": "at",
  "booking.nextSteps": "Next steps:",
  "booking.nextStep1": "Check your email for the session link",
  "booking.nextStep2": "Prepare headphones and microphone for the best experience",
  "booking.nextStep3": "Join on time to make the most of your session",
  "booking.bookAnother": "Book Another",
  "booking.goHome": "Go Home",

  // AI Practice Demo
  "aiPractice.badge": "AI Practice",
  "aiPractice.title": "Experience AI Speaking Practice",
  "aiPractice.subtitle": "Try our smart AI system to practice English speaking and receive detailed feedback",
  "aiPractice.step1": "Choose Type",
  "aiPractice.step2": "Choose Topic",
  "aiPractice.step3": "Choose Level",
  "aiPractice.step4": "Choose Mode",
  "aiPractice.step5": "Practice",
  "aiPractice.step6": "Feedback",
  "aiPractice.back": "Back",
  "aiPractice.ieltsTitle": "IELTS Speaking",
  "aiPractice.ieltsDesc": "Practice IELTS Speaking parts with AI acting as an examiner",
  "aiPractice.ieltsPart1": "Part 1: Personal questions",
  "aiPractice.ieltsPart2": "Part 2: Cue Card",
  "aiPractice.ieltsPart3": "Part 3: In-depth discussion",
  "aiPractice.conversationTitle": "Daily Conversation",
  "aiPractice.conversationDesc": "Practice communicating in real-life situations with AI",
  "aiPractice.conv1": "Ordering food",
  "aiPractice.conv2": "Making new friends",
  "aiPractice.conv3": "Job interview",
  "aiPractice.selectIelts": "Select IELTS Speaking Part",
  "aiPractice.selectConv": "Select Conversation Topic",
  "aiPractice.selectIeltsHint": "Choose the part you want to practice",
  "aiPractice.selectConvHint": "Choose a situation you want to practice",
  "aiPractice.inputPlaceholder": "Type your answer or press mic to speak...",
  "aiPractice.demoHint": "💡 This is a demo - in the full version, AI will analyze your actual voice",
  "aiPractice.overallScore": "Overall Score",
  "aiPractice.outOf9": "out of 9.0",
  "aiPractice.detailedAnalysis": "Detailed Analysis",
  "aiPractice.pronunciation": "Pronunciation",
  "aiPractice.grammar": "Grammar",
  "aiPractice.vocabulary": "Vocabulary",
  "aiPractice.fluency": "Fluency",
  "aiPractice.coherence": "Coherence",
  "aiPractice.strengths": "Strengths",
  "aiPractice.suggestions": "Suggestions for Improvement",
  "aiPractice.tryAgain": "Try This Topic Again",
  "aiPractice.newTopic": "Choose New Topic",
  "aiPractice.selectLevel": "Select Your Level",
  "aiPractice.selectLevelHint": "AI will adjust difficulty to match your proficiency",
  "aiPractice.level.beginner": "Beginner",
  "aiPractice.level.beginnerDesc": "CEFR A1-A2 • Simple vocabulary, short sentences",
  "aiPractice.level.beginnerFeature1": "Basic vocabulary",
  "aiPractice.level.beginnerFeature2": "Slow and clear speech",
  "aiPractice.level.beginnerFeature3": "Many helpful prompts",
  "aiPractice.level.intermediate": "Intermediate",
  "aiPractice.level.intermediateDesc": "CEFR B1-B2 • Natural conversation",
  "aiPractice.level.intermediateFeature1": "More complex sentences",
  "aiPractice.level.intermediateFeature2": "Gentle error correction",
  "aiPractice.level.intermediateFeature3": "Encouraged expansion",
  "aiPractice.level.advanced": "Advanced",
  "aiPractice.level.advancedDesc": "CEFR C1-C2 • In-depth discussion",
  "aiPractice.level.advancedFeature1": "Rich vocabulary",
  "aiPractice.level.advancedFeature2": "Idioms and complex structures",
  "aiPractice.level.advancedFeature3": "Critical thinking challenges",
  "aiPractice.selectMode": "Select Practice Mode",
  "aiPractice.selectModeHint": "Do you want to practice by voice or chat?",
  "aiPractice.mode.voice": "Voice Mode",
  "aiPractice.mode.voiceDesc": "Have a natural conversation with AI using your voice",
  "aiPractice.mode.voiceFeature1": "Talk like in real life",
  "aiPractice.mode.voiceFeature2": "Subtitle support",
  "aiPractice.mode.voiceFeature3": "Answer suggestions",
  "aiPractice.mode.chat": "Chat Mode",
  "aiPractice.mode.chatDesc": "Type your answers and receive detailed feedback",
  "aiPractice.mode.chatFeature1": "Time to think",
  "aiPractice.mode.chatFeature2": "Review conversation",
  "aiPractice.mode.chatFeature3": "Answer suggestions",
  "aiPractice.suggestedResponses": "Suggested responses:",
  "aiPractice.voice.title": "AI Speaking Practice",
  "aiPractice.voice.connected": "Connected!",
  "aiPractice.voice.error": "Connection error",
  "aiPractice.voice.captions": "Captions",
  "aiPractice.voice.aiSpeaking": "AI is speaking...",
  "aiPractice.voice.yourTurn": "Your turn!",
  "aiPractice.voice.listenCarefully": "Listen carefully",
  "aiPractice.voice.speakNow": "Speak your answer now",
  "aiPractice.voice.ready": "Ready to start",
  "aiPractice.voice.clickToStart": "Click the button below to begin",
  "aiPractice.voice.connecting": "Connecting...",
  "aiPractice.voice.startCall": "Start",
  "aiPractice.voice.endCall": "End",
  "aiPractice.voice.hint": "Speak clearly and naturally. AI will listen and respond.",
  "aiPractice.voice.finish": "Finish and view feedback",
  "aiPractice.voice.setupRequired": "ElevenLabs Agent setup required",
  "aiPractice.voice.setupHint": "Enter Agent ID from ElevenLabs to use voice mode",
  "aiPractice.voice.agentIdPlaceholder": "Enter ElevenLabs Agent ID",
  "aiPractice.voice.continue": "Continue",
  "aiPractice.voice.createAgentHint": "Create an agent at elevenlabs.io/conversational-ai",
  "aiPractice.voice.noAgentId": "Please enter an Agent ID",
  "aiPractice.voice.connectionFailed": "Unable to connect. Please try again.",
  "aiPractice.chat.title": "Chat Practice",
  "aiPractice.chat.hint": "Type your answer or select a suggestion above",
  "aiPractice.chat.finish": "Finish",
  "aiPractice.rateLimited": "Too many requests. Please try again later.",
  "aiPractice.paymentRequired": "More credits needed to continue.",
  "aiPractice.connectionError": "Connection error. Please try again.",
  "aiPractice.endPractice": "End practice",
  "aiPractice.analyzingPerformance": "Analyzing results...",
  "aiPractice.pleaseWait": "Please wait while AI evaluates your speaking",
  "aiPractice.feedbackError": "Unable to generate feedback. Showing default results.",

  // Common
  "common.month1": "January",
  "common.month2": "February",
  "common.month3": "March",
  "common.month4": "April",
  "common.month5": "May",
  "common.month6": "June",
  "common.month7": "July",
  "common.month8": "August",
  "common.month9": "September",
  "common.month10": "October",
  "common.month11": "November",
  "common.month12": "December",
  "common.sun": "Sun",
  "common.mon": "Mon",
  "common.tue": "Tue",
  "common.wed": "Wed",
  "common.thu": "Thu",
  "common.fri": "Fri",
  "common.sat": "Sat",
  "common.sunday": "Sunday",
  "common.monday": "Monday",
  "common.tuesday": "Tuesday",
  "common.wednesday": "Wednesday",
  "common.thursday": "Thursday",
  "common.friday": "Friday",
  "common.saturday": "Saturday",

  // Parent Dashboard
  "parent.badge": "For Parents",
  "parent.title": "Track Your Child's Learning Progress",
  "parent.subtitle": "View an overview of your child's learning progress, attendance, and achievements",
  "parent.selectChild": "Select child to view",
  "parent.progressVideos": "Progress Videos",
  "parent.beforeVideo": "Before the Course",
  "parent.afterVideo": "After the Course",
  "parent.entryTestRecording": "Entry test recording",
  "parent.graduationRecording": "Graduation recording",
  "parent.beforeVideoDesc": "Video recording of the student's speaking during the entry test before starting the program.",
  "parent.afterVideoDesc": "Video recording of the student's speaking upon completing the program.",
  "parent.demoNote": "This is a demo page. The data shown is sample illustration.",

  // Inaugural Program
  "inaugural.badge": "Inaugural Program",
  "inaugural.title": "Speaking Foundation Program",
  "inaugural.subtitle": "An 8-week course designed to build a solid English speaking foundation through a unique blended learning method.",
  "inaugural.overviewTitle": "Program Overview",
  "inaugural.programLength": "Duration",
  "inaugural.programLengthValue": "8 weeks",
  "inaugural.programFormat": "Learning format",
  "inaugural.programFormatValue": "Blended learning (Vietnamese teacher classes + Daily AI practice + Weekly 1-on-1 with foreign teacher)",
  "inaugural.targetLevel": "Target level",
  "inaugural.targetLevelValue": "CEFR A2–B1 (Students take a short entry test to ensure proper placement)",
  "inaugural.classSize": "Class size",
  "inaugural.classSizeValue": "15 students/class (1 teacher/group to maximize speaking time)",
  "inaugural.mentorPractice": "Mentor practice",
  "inaugural.mentorPracticeValue": "Weekly 1-on-1 sessions with a native mentor",
  "inaugural.aiPractice": "AI Speaking Practice",
  "inaugural.aiPracticeValue": "Unlimited access, practice anytime throughout the program",

  "inaugural.weeklyScheduleTitle": "Weekly Schedule",
  "inaugural.weeklyScheduleDesc": "Each week follows a consistent, purposeful rhythm, helping students progress from preparation → practice → real communication.",

  "inaugural.step1Title": "Learn With Vietnamese Teacher",
  "inaugural.step1Timing": "Beginning of the week",
  "inaugural.step1Intro": "The week begins with a session with a Vietnamese teacher, where students are introduced to the speaking focus and core communication skills for the week.",
  "inaugural.studentsWill": "In the session, students will:",
  "inaugural.step1Point1": "Learn the week's topic and speaking goals",
  "inaugural.step1Point2": "Practice speaking through guided activities and small group interactions",
  "inaugural.step1Point3": "Receive language support (vocabulary, sentence structures, speaking strategies)",
  "inaugural.step1Point4": "Build confidence in a supportive, low-pressure environment",
  "inaugural.step1Footer": "This session lays the foundation for all practice activities during the week.",

  "inaugural.step2Title": "Daily AI Speaking Practice",
  "inaugural.step2Timing": "During the week, at home",
  "inaugural.step2Intro": "After the in-class session, students practice speaking at home with AI tools, with unlimited access throughout the week.",
  "inaugural.aiAllows": "AI practice helps students:",
  "inaugural.step2Point1": "Review what they learned in class at their own pace",
  "inaugural.step2Point2": "Practice pronunciation, fluency, and sentence structure",
  "inaugural.step2Point3": "Repeat speaking exercises as many times as they want without pressure",
  "inaugural.step2Point4": "Build confidence before speaking with real people",
  "inaugural.step2Footer": "Short, frequent practice sessions help students build speaking habits and reduce anxiety over time.",

  "inaugural.step3Title": "1-on-1 Session With Mentor",
  "inaugural.step3Timing": "End of the week",
  "inaugural.step3Intro": "At the end of the week—usually Friday or weekend—students join an online 1-on-1 session with a native mentor.",
  "inaugural.step3Point1": "Apply what they've practiced during the week in real conversation",
  "inaugural.step3Point2": "Speak with a new but friendly listener",
  "inaugural.step3Point3": "Experience natural English usage and different accents",
  "inaugural.step3Point4": "Build confidence transitioning from practice to real communication",
  "inaugural.step3Footer": "The mentor session helps students \"level up\" by connecting classroom learning and AI practice with real-world interaction.",

  "inaugural.sampleWeekTitle": "Sample Schedule — Week 1",
  "inaugural.week1Focus": "Week 1 Focus",
  "inaugural.week1Theme": "Topic: Self & everyday world",
  "inaugural.week1Goal": "Speaking goal: Students introduce themselves briefly, with preparation, without avoiding speaking.",

  "inaugural.mondayTitle": "Monday",
  "inaugural.mondaySubtitle": "Class With Vietnamese Teacher",
  "inaugural.mondayFormat": "Format: Small group class (15 students, 1 teacher)",
  "inaugural.learnPractice": "Students learn and practice:",
  "inaugural.mondayPoint1": "Clear expectations and rules: Mistakes are normal and part of learning",
  "inaugural.mondayPoint2": "Guided self-introduction using sentence frames (e.g., \"I am...\", \"I usually...\", \"I like...\")",
  "inaugural.mondayPoint3": "Pair and small group speaking with preparation time",
  "inaugural.mondayPoint4": "Teacher models: natural pauses, how to hesitate and continue, how to recover when unsure",
  "inaugural.competencyFocus": "Competency focus (Week 1):",
  "inaugural.competency1": "Speaking: Supported self-introduction",
  "inaugural.competency2": "Listening to speak: Listen to familiar segments (names, routines, interests)",
  "inaugural.competency3": "Language resources: High-frequency personal vocabulary; present simple frame",
  "inaugural.competency4": "Pronunciation & clarity: Word stress; speaking slower for clarity",
  "inaugural.competency5": "Confidence & strategy: Using fillers (\"let me think\"), accepting silence without stopping",

  "inaugural.tueThuTitle": "Tuesday–Thursday",
  "inaugural.tueThuSubtitle": "Daily AI Speaking Practice",
  "inaugural.tueThuFormat": "Format: Short daily practice sessions (10–15 min each) | Access: Unlimited throughout the week",
  "inaugural.studentsDo": "What students do:",
  "inaugural.tueThuPoint1": "Practice self-introduction with low-pressure AI prompts",
  "inaugural.tueThuPoint2": "Repeat speaking exercises as many times as needed",
  "inaugural.tueThuPoint3": "Preview and review key vocabulary for class use",
  "inaugural.tueThuPoint4": "Practice speaking without fear of judgment",
  "inaugural.aiProvides": "What AI provides:",
  "inaugural.aiFeedbackDesc": "Neutral content feedback, focusing on: completion, length, clarity (not grammar accuracy)",
  "inaugural.aiPurpose": "AI purpose this week: Help students safely rehearse speaking and build comfort before speaking with real people.",

  "inaugural.fridayTitle": "Friday or Weekend",
  "inaugural.fridaySubtitle": "1-on-1 Session With Mentor",
  "inaugural.fridayFormat": "Format: Personal session with a native mentor",
  "inaugural.inSession": "In the session:",
  "inaugural.fridayPoint1": "Build rapport through conversation based on Week 1 topic",
  "inaugural.fridayPoint2": "Students introduce themselves and talk about daily life",
  "inaugural.fridayPoint3": "Mentor positively reflects on student's language",
  "inaugural.fridayPoint4": "Focus on comfort, clarity, and encouragement",
  "inaugural.mentorsDoNot": "Mentors DO NOT:",
  "inaugural.mentorNoDoDesc": "No testing, no heavy correction, no pressure",
  "inaugural.mentorPurpose": "Purpose of the mentor session: Help students transition practice into real communication with a friendly listener.",

  "inaugural.week1Evidence": "Week 1 Evidence & Results",
  "inaugural.byEndOfWeek1": "By End of Week 1:",
  "inaugural.evidence1": "Students complete a baseline speaking recording",
  "inaugural.evidence2": "Students complete a confidence self-assessment (S-FLCAS pre)",
  "inaugural.evidence3": "Teachers and mentors establish a clear starting point for progress",
  "inaugural.evidenceNote": "This evidence is used to support learning, not to evaluate performance.",

  "inaugural.exclusiveBenefits": "Exclusive Benefits",
  "inaugural.benefitsTitle": "Inaugural Cohort Benefits",
  "inaugural.benefitsDesc": "The upcoming group will be our inaugural cohort—the first students to experience Lingriser's full speaking foundation program.",
  "inaugural.benefit1Title": "Tuition support",
  "inaugural.benefit1Desc": "For this program",
  "inaugural.8weekProgram": "8-week program",
  "inaugural.benefit2Title": "Lifetime tuition benefits",
  "inaugural.benefit2Desc": "For future Lingriser programs",
  "inaugural.benefitsFooter": "These benefits recognize families who trust Lingriser as we launch our complete learning pathway.",

  "inaugural.registerTitle": "Register Interest (No Obligation)",
  "inaugural.registerSubtitle": "This form is not an enrollment registration and does not require payment.",
  "inaugural.registerNote": "Registering interest allows us to:",
  "inaugural.registerBenefit1": "Share complete detailed program information",
  "inaugural.registerBenefit2": "Contact you when registration opens",
  "inaugural.registerBenefit3": "Reserve inaugural cohort benefits for you",
  "inaugural.parentName": "Parent name",
  "inaugural.parentNamePlaceholder": "Enter full name",
  "inaugural.phone": "Phone number",
  "inaugural.phonePlaceholder": "Enter phone number",
  "inaugural.email": "Email",
  "inaugural.emailPlaceholder": "Enter email address",
  "inaugural.submit": "Register Interest",
  "inaugural.submitting": "Submitting...",
  "inaugural.contactNote": "We will contact you before the program starts.",
  "inaugural.formSuccess": "Successfully registered! We will contact you soon.",
  "inaugural.formError": "An error occurred. Please try again.",
  "inaugural.pleaseSelectIntent": "Please let us know if you'd like to register.",
  "inaugural.primaryGoalQuestion": "What is your primary goal when choosing a program for your child?",
  "inaugural.goalAcademic": "Improve academic results (grades, tests)",
  "inaugural.goalConfidence": "Build confidence in speaking English",

  "inaugural.wantsToSignupQuestion": "Would you like to sign up for the Speaking Foundation program?",
  "inaugural.yesInterested": "Yes, I'd like to sign up",
  "inaugural.noNotInterested": "No, I'm not interested at this time",
  "inaugural.whatInterestedYou": "What interested you about the program? (Optional)",
  "inaugural.interestReasonPlaceholder": "Share what attracted you most about this program...",
  "inaugural.whyNotInterested": "Could you share your reason? This will help us improve. (Optional)",
  "inaugural.rejectionReasonPlaceholder": "E.g., pricing, scheduling, need more info...",

  // Instructor Section
  "inaugural.instructorTitle": "Program Instructor",
  "inaugural.instructorSubtitle": "Learn with an experienced English teaching expert",
  "inaugural.instructorName": "Mr. Tran Quoc Khai",
  "inaugural.instructorRole": "Instructor - Speaking Foundation Program",
  "inaugural.qualifications": "Qualifications & Certifications",
  "inaugural.qual1": "M.A. in English Teaching (TEFL/TESOL) - Can Tho University",
  "inaugural.experience": "Teaching Experience",
  "inaugural.exp1": "Over 6 years of experience teaching conversational English with film and video methods",
  "inaugural.instructorQuote": "I believe every student can confidently communicate in English when given the right methods and learning environment.",

  // Real Results
  "results.title": "See Real Results",
  "results.subtitle": "Compare English speaking skills before and after the program",
  "results.before": "Before the Program",
  "results.after": "After the Program",
  "results.entryTest": "Entry test",
  "results.graduation": "Graduation",
  "results.demoNote": "Videos are used for illustration purposes, not actual students.",
  "results.play": "Play",
  "results.pause": "Pause",
  "results.mute": "Mute",
  "results.unmute": "Unmute",
  "results.viewProgram": "View Program",
};

const translations: Record<Language, Record<string, string>> = { vi, en };

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("lingriser-lang") as Language) || "vi";
    }
    return "vi";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lingriser-lang", lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.vi[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
