import { createContext, useContext, ReactNode } from "react";

interface LanguageContextType {
  language: "vi";
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  // Navigation
  "nav.home": "Trang Chủ",
  "nav.program": "Chương Trình",
  "nav.forStudents": "Dành Cho Học Sinh",
  "nav.forParents": "Dành Cho Phụ Huynh",
  "nav.aiPractice": "Luyện Tập với AI",
  "nav.booking": "Đặt Lịch với Mentor",
  "nav.parentDashboard": "Bảng Điều Khiển Phụ Huynh",
  "nav.login": "Đăng nhập",
  "nav.register": "Đăng ký",

  // Hero
  "hero.title": "Nâng Trình Giao Tiếp Tiếng Anh với",
  "hero.ai": "AI",
  "hero.and": "và",
  "hero.nativeMentor": "Mentor Bản Xứ",
  "hero.subtitle":
    "Một giải pháp khoa học và toàn diện giúp bạn vượt qua nỗi sợ để tự tin giao tiếp và đạt được điểm số mơ ước.",
  "hero.cta": "Khám phá điều gì đang cản trở bạn",
  "hero.painPoint1": "Em không dám giao tiếp vì sợ nói sai",
  "hero.painPoint2": "Em ít được luyện nói trên lớp",
  "hero.painPoint3": "Em luôn cảm thấy căng thẳng khi nói tiếng Anh",

  // Evidence
  "evidence.title": "Chuyên môn uy tín, nền tảng khoa học vững chắc",
  "evidence.ivyLeague": "Xây dựng bởi các chuyên gia từ các trường Ivy League - Mỹ",
  "evidence.cefr": "Bám sát chuẩn CEFR A2–B1* (tương đương IELTS 3.0–5.0)**",
  "evidence.cefrNote1":
    "* CEFR là chuẩn năng lực tiếng Anh quốc tế được sử dụng trong chương trình học và các kỳ thi như TOEFL, IELTS.",
  "evidence.cefrNote2": "** theo khung quy đổi của Cambridge English.",
  "evidence.flcas": "Dựa trên thang đo S-FLCAS***",
  "evidence.flcasNote":
    "*** FLCAS, phát triển bởi Đại học Texas tại Austin, là một trong những công cụ quan trọng nhất để đo lường lo âu khi nói tiếng Anh.",

  // Support
  "support.title": "Hỗ trợ đúng kỹ năng bạn cần nhất",
  "support.notAlone": "Nếu bạn thấy kỹ năng nói khó, bạn không cô đơn.",
  "support.stat1Value": "7/10",
  "support.stat1Label": "học sinh cho biết Nói là kỹ năng yếu nhất",
  "support.stat2Value": "Lo âu là rào cản lớn nhất",
  "support.stat2Label": "sợ bị cười (95%), sợ sai (86%), thiếu tự tin (75%)",
  "support.stat3Value": "5.6–5.7",
  "support.stat3Label": "Nói là kỹ năng có điểm thấp nhất của thí sinh Việt Nam theo báo cáo IELTS gần đây",
  "support.systemProblem": "Không phải do bạn — mà do hệ thống",
  "support.systemIntro": "Nói là kỹ năng ít được dạy và thực hành nhất. Hơn",
  "support.systemPercent": "70%",
  "support.systemTeachers": "giáo viên tiếng Anh tại Việt Nam cho biết:",
  "support.issue1": "Sĩ số quá đông để cho học sinh thời gian luyện nói",
  "support.issue2": "Không đủ thời lượng trên lớp",
  "support.issue3": "Hoạt động nói cần nhiều chuẩn bị",
  "support.issue4": "Học sinh quá ngại hoặc quá lo lắng nếu không có hỗ trợ",

  // Solution
  "solution.title": "Lingriser Learning Loop",
  "solution.subtitle":
    "Phương pháp độc quyền, phối hợp 3 thành phần giúp bạn tăng tự tin, giao tiếp lưu loát và chuẩn bị sẵn sàng cho các kỳ thi.",
  "solution.learnTitle": "Xây nền tảng vững chắc",
  "solution.learnDesc": "Học trên lớp với giáo viên để được hướng dẫn cặn kẽ những nội dung khó tự luyện",
  "solution.loopTitle": "Tự luyện hàng ngày với AI",
  "solution.loopDesc": "Luyện nói thoải mái, không ngại ngùng, và được AI sửa sai lập tức mọi lúc mọi nơi",
  "solution.levelUpTitle": "Nâng tầm với mentor bản xứ",
  "solution.levelUpDesc":
    "Trò chuyện trực tuyến với mentor bản xứ để tăng phản xạ, phát âm, tâm lý tự tin cho các kỳ thi.",

  // Features
  "features.title": "Điểm khác biệt của Lingriser",
  "features.subtitle": "Phương pháp đột phá kết hợp công nghệ AI tiên tiến với chuyên môn của con người",
  "features.curriculum": "Giáo trình sát đề thi",
  "features.curriculumDesc":
    "Bài học chuẩn CEFR, tâp trung các kỹ năng mục tiêu cần thiết để thành công trong kỳ thi thực tế.",
  "features.aiPractice": "Luyện nói cùng AI",
  "features.aiPracticeDesc":
    "Luyện nói không áp lực hay ngại sai với AI mọi lúc mọi nơi, để tăng cường sự tự tin và độ lưu loát.",
  "features.mentor": "Mentor bản xứ",
  "features.mentorDesc": "Học trực tuyến 1-1 với người bản xứ chi phí hợp lý để luyện phát âm và phản xạ tự nhiên",
  "features.riseMeter": "Tiến bộ với Rise Meter™",
  "features.riseMeterDesc":
    "Công cụ theo dõi tiến trình học tập đột phá, giúp bạn liên tục tiến bộ và nâng cao điểm số.",
  "features.personalized": "Lộ trình học cá nhân hóa",
  "features.personalizedDesc":
    "Các bài luyện tập được điều chỉnh linh hoạt theo nhu cầu và tiến độ để đạt kết quả nhanh và tối ưu hơn.",

  // Why It Works
  "why.title": "Tại Sao Phương Pháp Này Hiệu Quả",
  "why.subtitle":
    "Dựa trên nghiên cứu hàng đầu từ Đại học Iowa State, Texas A&M, Đại học Hawai'i và University College London, Lingriser kết hợp các yếu tố đã được chứng minh giúp cải thiện kỹ năng nói:",
  "why.aiTitle": "Luyện Tập Với AI",
  "why.aiDesc": "Phản hồi tức thì giúp tăng cường phát âm, độ lưu loát và độ chính xác.",
  "why.mentorTitle": "Hội Thoại Với Mentor Bản Xứ",
  "why.mentorDesc":
    "Tương tác với người nói thành thạo giúp xây dựng phản xạ tự nhiên, sự tự tin và kỹ năng giao tiếp thực tế.",
  "why.loopTitle": "Vòng Lặp Luyện Tập Giảm Lo Lắng",
  "why.loopDesc":
    "Các buổi AI áp lực thấp kết hợp với tương tác mentor hỗ trợ giúp giảm lo lắng khi nói và tăng tốc sự tự tin.",

  // How It Works
  "how.title": "Cách Thức Hoạt Động",
  "how.subtitle": "Hành trình từ lo lắng đến tự tin trong 6 bước đơn giản",
  "how.step1": "Đăng Ký",
  "how.step1Desc": "Đặt mục tiêu, trình độ và sở thích của bạn",
  "how.step2": "Làm Bài Đánh Giá Đầu Vào",
  "how.step2Desc": "Xác định điểm mạnh/yếu và mức độ tự tin.",
  "how.step3": "Tham Gia Lớp Học Hàng Tuần",
  "how.step3Desc": "Xây dựng nền tảng với giáo viên trên lớp",
  "how.step4": "Luyện Tập Hàng Ngày với AI",
  "how.step4Desc": "Tăng độ lưu loát và tự tin.",
  "how.step5": "Giao tiếp với Mentor bản xứ",
  "how.step5Desc": "Nâng cao phản xạ giao tiếp",
  "how.step6": "Theo Dõi Tiến Trình với Rise Meter™",
  "how.step6Desc": "Cập nhật tiến bộ liên tục mỗi tuần.",

  // Pricing
  "pricing.title": "Học Phí Thông Minh",
  "pricing.subtitle": "Các gói học phí linh hoạt, phù hợp với mọi nhu cầu và khả năng tài chính",
  "pricing.cohort": "Theo Khoá",
  "pricing.flexible": "Theo Nhu Cầu",
  "pricing.6weeks": "6 Tuần",
  "pricing.8weeks": "8 Tuần",
  "pricing.12weeks": "12 Tuần",
  "pricing.bestValue": "Giá Trị Tốt Nhất",
  "pricing.mostSavings": "Tiết Kiệm Nhất",
  "pricing.maxResults": "Kết Quả Tối Đa",
  "pricing.weeklyClass": "1 buổi học trên lớp mỗi tuần",
  "pricing.limitedAI": "3 buổi luyện tập AI mỗi tuần",
  "pricing.unlimitedAI": "Luyện tập AI không giới hạn",
  "pricing.weeklyMentor45": "1 buổi mentor 45 phút mỗi tuần",
  "pricing.weeklyMentor45x2": "2 buổi mentor 45 phút mỗi tuần",
  "pricing.riseMeterTracking": "Theo dõi tiến trình Rise Meter™",
  "pricing.cefrCurriculum": "Giáo trình chuẩn CEFR",
  "pricing.signUp": "Đăng Ký Ngay",
  "pricing.aiOnly": "Chỉ Luyện Tập AI",
  "pricing.aiOnlyDesc": "Hoàn hảo cho người tự học",
  "pricing.mentorOnly": "Chỉ Mentor",
  "pricing.mentorOnlyDesc": "Buổi học mentor một lần",
  "pricing.combo": "AI + Mentor Kết Hợp",
  "pricing.comboDesc": "Tốt nhất của cả hai",
  "pricing.unlimitedAIPractice": "Luyện nói AI không giới hạn",
  "pricing.realTimeFeedback": "Phản hồi theo thời gian thực",
  "pricing.progressTracking": "Theo dõi tiến trình",
  "pricing.30minSession": "Buổi học 1-1 30 phút",
  "pricing.nativeMentor": "Mentor người bản xứ",
  "pricing.personalizedFeedback": "Phản hồi cá nhân hóa",
  "pricing.4sessions": "4 buổi mentor mỗi tháng",
  "pricing.fullTracking": "Theo dõi tiến trình đầy đủ",
  "pricing.start": "Bắt Đầu",

  // FAQ
  "faq.title": "Câu Hỏi Thường Gặp",
  "faq.subtitle": "Tất cả những gì bạn cần biết về Lingriser",
  "faq.q1": "Chương trình bao gồm những gì?",
  "faq.a1":
    "Chương trình đầy đủ bao gồm các buổi học hàng tuần với giáo viên, luyện nói với AI không giới hạn, các buổi huấn luyện với mentor hàng tuần, và quyền truy cập hệ thống theo dõi tiến trình Rise Meter™. Tất cả đều theo chuẩn CEFR và được thiết kế để xây dựng sự tự tin khi nói.",
  "faq.q2": "Giáo viên và mentor là ai?",
  "faq.a2":
    "Giáo viên của chúng tôi là những nhà giáo dục tiếng Anh có chứng chỉ với kinh nghiệm giảng dạy tại Việt Nam. Các mentor là người bản xứ nói tiếng Anh hoặc những người nói tiếng Anh trình độ cao đã được đào tạo để cung cấp phản hồi hỗ trợ và mang tính xây dựng.",
  "faq.q3": "Làm thế nào để đăng ký và thanh toán?",
  "faq.a3":
    "Đăng ký rất đơn giản qua website của chúng tôi. Chúng tôi chấp nhận chuyển khoản ngân hàng, thẻ tín dụng và các phương thức thanh toán phổ biến tại Việt Nam.",
  "faq.q4": "Chương trình giúp gì cho việc khắc phục lo lắng và phát triển kỹ năng nói?",
  "faq.a4":
    "Chúng tôi sử dụng phương pháp dựa trên nghiên cứu kết hợp luyện tập AI áp lực thấp (hoàn hảo cho người học lo lắng), các bài học có cấu trúc trên lớp, và huấn luyện mentor hỗ trợ.",
  "faq.q5": "Học sinh theo dõi tiến trình như thế nào?",
  "faq.a5":
    "Hệ thống Rise Meter™ của chúng tôi cung cấp cập nhật hàng tuần về độ lưu loát, mức độ tự tin và sự sẵn sàng cho kỳ thi.",
  "faq.q6": "Chương trình phù hợp với độ tuổi hoặc trình độ nào?",
  "faq.a6": "Chương trình được thiết kế cho học sinh lớp 6–12 với trình độ CEFR A2–B1.",
  "faq.q7": "Tôi có thể thử các buổi AI hoặc mentor mà không cần tham gia khóa học không?",
  "faq.a7": "Có! Chúng tôi cung cấp các tùy chọn thanh toán linh hoạt theo nhu cầu.",
  "faq.q8": "Chương trình có quá nặng không? Tôi không muốn con bị áp lực.",
  "faq.a8": "Không hề! Đây không phải chương trình truyền thống nặng về ngữ pháp và nhàm chán. Lingriser tập trung tạo môi trường tương tác, thực hành để học sinh tự nhiên đắm mình trong môi trường nói tiếng Anh, phát triển phản xạ ngôn ngữ và sử dụng tiếng Anh tự nhiên trong các bối cảnh và tình huống thực tế thông qua các phương pháp học tập chủ động như đóng vai, luyện tập theo cặp, và nhiều hoạt động khác.",
  "faq.q9": "Con tôi có còn học ngữ pháp, từ vựng, đọc, nghe như bình thường không?",
  "faq.a9": "Có! Mặc dù chương trình tập trung vào kỹ năng nói, học sinh vẫn học ngữ pháp, từ vựng, đọc và nghe như những kỹ năng hỗ trợ để phát triển khả năng giao tiếp. Chương trình Lingriser được thiết kế để bổ sung, không phải thay thế chương trình tiếng Anh truyền thống ở trường.",

  // CTA
  "cta.limited": "Số lượng có hạn cho khóa học tiếp theo",
  "cta.title": "Bắt Đầu Hành Trình Cùng Chúng Tôi",
  "cta.subtitle": "Sẵn sàng xây dựng sự tự tin và kết quả nói thực sự?",
  "cta.startNow": "Bắt Đầu Ngay",
  "cta.bookConsult": "Đặt Lịch Tư Vấn",
  "cta.noCard": "✓ Không cần thẻ tín dụng • ✓ Tư vấn miễn phí",

  // Booking Demo
  "booking.title": "Đặt Lịch với Mentor",
  "booking.subtitle": "Chọn mentor phù hợp và đặt lịch học 1-1 để cải thiện kỹ năng giao tiếp tiếng Anh",
  "booking.step1": "Chọn Mentor",
  "booking.step2": "Chọn Thời Gian",
  "booking.step3": "Xác Nhận",
  "booking.selectMentor": "Chọn Mentor",
  "booking.reviews": "đánh giá",
  "booking.back": "Quay lại",
  "booking.timeSlots": "Khung giờ",
  "booking.selectDate": "Chọn ngày để xem khung giờ",
  "booking.confirmTime": "Xác nhận thời gian",
  "booking.pleaseSelectDate": "Vui lòng chọn ngày trên lịch",
  "booking.backToTime": "Quay lại chọn thời gian",
  "booking.confirmBooking": "Xác nhận đặt lịch",
  "booking.reviewInfo": "Vui lòng kiểm tra thông tin trước khi xác nhận",
  "booking.mentor": "Mentor",
  "booking.date": "Ngày",
  "booking.time": "Giờ",
  "booking.sessionType": "Hình thức học:",
  "booking.videoCall": "Học với GV nước ngoài",
  "booking.voiceCall": "Voice call",
  "booking.mentorSpecialties": "Chuyên môn của mentor:",
  "booking.confirmBtn": "Xác nhận đặt lịch",
  "booking.demoNote": "* Đây là trang demo. Trong thực tế, bạn sẽ nhận được email xác nhận.",
  "booking.success": "Đặt lịch thành công!",
  "booking.successMsg": "Bạn đã đặt lịch học với",
  "booking.at": "vào",
  "booking.nextSteps": "Bước tiếp theo:",
  "booking.nextStep1": "Kiểm tra email để nhận link tham gia buổi học",
  "booking.nextStep2": "Chuẩn bị tai nghe và micro để có trải nghiệm tốt nhất",
  "booking.nextStep3": "Tham gia đúng giờ để tận dụng tối đa thời gian học",
  "booking.bookAnother": "Đặt lịch khác",
  "booking.goHome": "Về trang chủ",

  // AI Practice Demo
  "aiPractice.badge": "Luyện Tập với AI",
  "aiPractice.title": "Trải Nghiệm Luyện Nói với AI",
  "aiPractice.subtitle": "Thử nghiệm hệ thống AI thông minh giúp bạn luyện nói tiếng Anh và nhận phản hồi chi tiết",
  "aiPractice.step1": "Chọn Loại",
  "aiPractice.step2": "Chọn Chủ Đề",
  "aiPractice.step3": "Chọn Cấp Độ",
  "aiPractice.step4": "Chọn Chế Độ",
  "aiPractice.step5": "Luyện Tập",
  "aiPractice.step6": "Phản Hồi",
  "aiPractice.back": "Quay lại",
  "aiPractice.ieltsTitle": "IELTS Speaking",
  "aiPractice.ieltsDesc": "Luyện tập các phần thi IELTS Speaking với AI đóng vai giám khảo",
  "aiPractice.ieltsPart1": "Part 1: Câu hỏi cá nhân",
  "aiPractice.ieltsPart2": "Part 2: Cue Card",
  "aiPractice.ieltsPart3": "Part 3: Thảo luận chuyên sâu",
  "aiPractice.conversationTitle": "Hội Thoại Hằng Ngày",
  "aiPractice.conversationDesc": "Thực hành giao tiếp trong các tình huống thực tế với AI",
  "aiPractice.conv1": "Gọi món ăn",
  "aiPractice.conv2": "Kết bạn mới",
  "aiPractice.conv3": "Phỏng vấn xin việc",
  "aiPractice.selectIelts": "Chọn Phần Thi IELTS Speaking",
  "aiPractice.selectConv": "Chọn Chủ Đề Hội Thoại",
  "aiPractice.selectIeltsHint": "Lựa chọn phần thi bạn muốn luyện tập",
  "aiPractice.selectConvHint": "Chọn tình huống bạn muốn thực hành",
  "aiPractice.inputPlaceholder": "Nhập câu trả lời hoặc nhấn mic để nói...",
  "aiPractice.demoHint": "💡 Đây là bản demo - trong phiên bản đầy đủ, AI sẽ phân tích giọng nói thực của bạn",
  "aiPractice.overallScore": "Điểm Tổng Thể",
  "aiPractice.outOf9": "trên thang điểm 9.0",
  "aiPractice.detailedAnalysis": "Phân Tích Chi Tiết",
  "aiPractice.pronunciation": "Phát âm",
  "aiPractice.grammar": "Ngữ pháp",
  "aiPractice.vocabulary": "Từ vựng",
  "aiPractice.fluency": "Lưu loát",
  "aiPractice.coherence": "Mạch lạc",
  "aiPractice.strengths": "Điểm Mạnh",
  "aiPractice.suggestions": "Gợi Ý Cải Thiện",
  "aiPractice.tryAgain": "Thử Lại Chủ Đề Này",
  "aiPractice.newTopic": "Chọn Chủ Đề Mới",
  "aiPractice.selectLevel": "Chọn Cấp Độ Của Bạn",
  "aiPractice.selectLevelHint": "AI sẽ điều chỉnh độ khó phù hợp với trình độ của bạn",
  "aiPractice.level.beginner": "Người Mới Bắt Đầu",
  "aiPractice.level.beginnerDesc": "CEFR A1-A2 • Từ vựng đơn giản, câu ngắn",
  "aiPractice.level.beginnerFeature1": "Từ vựng cơ bản",
  "aiPractice.level.beginnerFeature2": "Nói chậm và rõ ràng",
  "aiPractice.level.beginnerFeature3": "Nhiều gợi ý hỗ trợ",
  "aiPractice.level.intermediate": "Trung Cấp",
  "aiPractice.level.intermediateDesc": "CEFR B1-B2 • Hội thoại tự nhiên",
  "aiPractice.level.intermediateFeature1": "Câu phức tạp hơn",
  "aiPractice.level.intermediateFeature2": "Sửa lỗi nhẹ nhàng",
  "aiPractice.level.intermediateFeature3": "Khuyến khích mở rộng",
  "aiPractice.level.advanced": "Nâng Cao",
  "aiPractice.level.advancedDesc": "CEFR C1-C2 • Thảo luận chuyên sâu",
  "aiPractice.level.advancedFeature1": "Từ vựng phong phú",
  "aiPractice.level.advancedFeature2": "Thành ngữ và cấu trúc phức tạp",
  "aiPractice.level.advancedFeature3": "Thách thức tư duy",
  "aiPractice.selectMode": "Chọn Chế Độ Luyện Tập",
  "aiPractice.selectModeHint": "Bạn muốn luyện nói bằng giọng nói hay chat?",
  "aiPractice.mode.voice": "Chế Độ Giọng Nói",
  "aiPractice.mode.voiceDesc": "Trò chuyện tự nhiên với AI bằng giọng nói của bạn",
  "aiPractice.mode.voiceFeature1": "Nói chuyện như thật",
  "aiPractice.mode.voiceFeature2": "Phụ đề hỗ trợ",
  "aiPractice.mode.voiceFeature3": "Gợi ý câu trả lời",
  "aiPractice.mode.chat": "Chế Độ Chat",
  "aiPractice.mode.chatDesc": "Nhập câu trả lời và nhận phản hồi chi tiết",
  "aiPractice.mode.chatFeature1": "Thời gian suy nghĩ",
  "aiPractice.mode.chatFeature2": "Xem lại hội thoại",
  "aiPractice.mode.chatFeature3": "Gợi ý câu trả lời",
  "aiPractice.suggestedResponses": "Gợi ý câu trả lời:",
  "aiPractice.voice.title": "Luyện Nói với AI",
  "aiPractice.voice.connected": "Đã kết nối!",
  "aiPractice.voice.error": "Lỗi kết nối",
  "aiPractice.voice.captions": "Phụ đề",
  "aiPractice.voice.aiSpeaking": "AI đang nói...",
  "aiPractice.voice.yourTurn": "Đến lượt bạn!",
  "aiPractice.voice.listenCarefully": "Hãy lắng nghe cẩn thận",
  "aiPractice.voice.speakNow": "Hãy nói câu trả lời của bạn",
  "aiPractice.voice.ready": "Sẵn sàng bắt đầu",
  "aiPractice.voice.clickToStart": "Nhấn nút bên dưới để bắt đầu",
  "aiPractice.voice.connecting": "Đang kết nối...",
  "aiPractice.voice.startCall": "Bắt đầu",
  "aiPractice.voice.endCall": "Kết thúc",
  "aiPractice.voice.hint": "Nói rõ ràng và tự nhiên. AI sẽ lắng nghe và phản hồi.",
  "aiPractice.voice.finish": "Hoàn thành và xem phản hồi",
  "aiPractice.voice.setupRequired": "Cần cấu hình ElevenLabs Agent",
  "aiPractice.voice.setupHint": "Nhập Agent ID từ ElevenLabs để sử dụng chế độ giọng nói",
  "aiPractice.voice.agentIdPlaceholder": "Nhập ElevenLabs Agent ID",
  "aiPractice.voice.continue": "Tiếp tục",
  "aiPractice.voice.createAgentHint": "Tạo agent tại elevenlabs.io/conversational-ai",
  "aiPractice.voice.noAgentId": "Vui lòng nhập Agent ID",
  "aiPractice.voice.connectionFailed": "Không thể kết nối. Vui lòng thử lại.",
  "aiPractice.chat.title": "Chat Luyện Tập",
  "aiPractice.chat.hint": "Nhập câu trả lời hoặc chọn gợi ý bên trên",
  "aiPractice.chat.finish": "Hoàn thành",
  "aiPractice.rateLimited": "Quá nhiều yêu cầu. Vui lòng thử lại sau.",
  "aiPractice.paymentRequired": "Cần nạp thêm credits để tiếp tục.",
  "aiPractice.connectionError": "Lỗi kết nối. Vui lòng thử lại.",
  "aiPractice.endPractice": "Kết thúc luyện tập",
  "aiPractice.analyzingPerformance": "Đang phân tích kết quả...",
  "aiPractice.pleaseWait": "Vui lòng đợi trong giây lát khi AI đánh giá bài nói của bạn",
  "aiPractice.feedbackError": "Không thể tạo phản hồi. Đang hiển thị kết quả mặc định.",

  // Common
  "common.month1": "Tháng 1",
  "common.month2": "Tháng 2",
  "common.month3": "Tháng 3",
  "common.month4": "Tháng 4",
  "common.month5": "Tháng 5",
  "common.month6": "Tháng 6",
  "common.month7": "Tháng 7",
  "common.month8": "Tháng 8",
  "common.month9": "Tháng 9",
  "common.month10": "Tháng 10",
  "common.month11": "Tháng 11",
  "common.month12": "Tháng 12",
  "common.sun": "CN",
  "common.mon": "T2",
  "common.tue": "T3",
  "common.wed": "T4",
  "common.thu": "T5",
  "common.fri": "T6",
  "common.sat": "T7",
  "common.sunday": "Chủ nhật",
  "common.monday": "Thứ hai",
  "common.tuesday": "Thứ ba",
  "common.wednesday": "Thứ tư",
  "common.thursday": "Thứ năm",
  "common.friday": "Thứ sáu",
  "common.saturday": "Thứ bảy",

  // Parent Dashboard
  "parent.badge": "Dành Cho Phụ Huynh",
  "parent.title": "Theo Dõi Tiến Trình Học Của Con",
  "parent.subtitle": "Xem tổng quan về tiến độ học tập, điểm danh và thành tích của con bạn",
  "parent.selectChild": "Chọn con để xem",
  "parent.progressVideos": "Video Tiến Bộ",
  "parent.beforeVideo": "Trước Khóa Học",
  "parent.afterVideo": "Sau Khóa Học",
  "parent.entryTestRecording": "Bài kiểm tra đầu vào",
  "parent.graduationRecording": "Bài tốt nghiệp",
  "parent.beforeVideoDesc": "Video ghi lại bài nói của học sinh trong bài kiểm tra đầu vào trước khi bắt đầu chương trình.",
  "parent.afterVideoDesc": "Video ghi lại bài nói của học sinh khi hoàn thành chương trình.",
  "parent.demoNote": "Đây là trang demo. Dữ liệu được hiển thị là mẫu minh họa.",

  // Inaugural Program
  "inaugural.badge": "Chương Trình Khai Giảng",
  "inaugural.title": "Chương Trình Nền Tảng Giao Tiếp",
  "inaugural.subtitle": "Khóa học 8 tuần được thiết kế để xây dựng nền tảng nói tiếng Anh vững chắc thông qua phương pháp học kết hợp độc đáo.",
  "inaugural.overviewTitle": "Tổng Quan Chương Trình",
  "inaugural.programLength": "Thời lượng",
  "inaugural.programLengthValue": "8 tuần",
  "inaugural.programFormat": "Hình thức học",
  "inaugural.programFormatValue": "Học kết hợp (Học với GV Việt Nam + Luyện nói AI hàng ngày + Học 1-1 với GV nước ngoài hàng tuần)",
  "inaugural.targetLevel": "Trình độ mục tiêu",
  "inaugural.targetLevelValue": "CEFR A2–B1 (Học sinh làm bài kiểm tra đầu vào ngắn để đảm bảo xếp lớp phù hợp)",
  "inaugural.classSize": "Sĩ số lớp",
  "inaugural.classSizeValue": "15 học sinh/lớp (1 giáo viên/nhóm để tối đa thời gian nói)",
  "inaugural.mentorPractice": "Luyện tập với Mentor",
  "inaugural.mentorPracticeValue": "Buổi học 1-1 hàng tuần với mentor bản xứ",
  "inaugural.aiPractice": "Luyện nói với AI",
  "inaugural.aiPracticeValue": "Truy cập không giới hạn, luyện tập mọi lúc trong suốt chương trình",

  "inaugural.weeklyScheduleTitle": "Lịch Học Hàng Tuần",
  "inaugural.weeklyScheduleDesc": "Mỗi tuần theo một nhịp học nhất quán và có chủ đích, giúp học sinh chuyển từ chuẩn bị → luyện tập → giao tiếp thực tế.",

  "inaugural.step1Title": "Học Với Giáo Viên Việt Nam",
  "inaugural.step1Timing": "Đầu tuần",
  "inaugural.step1Intro": "Tuần bắt đầu với buổi học với giáo viên Việt Nam, nơi học sinh được giới thiệu trọng tâm nói và các kỹ năng giao tiếp cốt lõi trong tuần.",
  "inaugural.studentsWill": "Trong buổi học, học sinh sẽ:",
  "inaugural.step1Point1": "Tìm hiểu chủ đề và mục tiêu nói trong tuần",
  "inaugural.step1Point2": "Luyện nói thông qua các hoạt động có hướng dẫn và tương tác nhóm nhỏ",
  "inaugural.step1Point3": "Nhận hỗ trợ ngôn ngữ (từ vựng, cấu trúc câu, chiến lược nói)",
  "inaugural.step1Point4": "Xây dựng sự tự tin trong môi trường hỗ trợ, ít áp lực",
  "inaugural.step1Footer": "Buổi học này tạo nền tảng cho tất cả các hoạt động luyện tập trong tuần.",

  "inaugural.step2Title": "Luyện Nói AI Hàng Ngày",
  "inaugural.step2Timing": "Trong tuần, tại nhà",
  "inaugural.step2Intro": "Sau buổi học trên lớp, học sinh luyện nói tại nhà với công cụ AI, truy cập không giới hạn trong suốt tuần.",
  "inaugural.aiAllows": "Luyện tập AI giúp học sinh:",
  "inaugural.step2Point1": "Ôn luyện những gì đã học trên lớp theo tốc độ riêng",
  "inaugural.step2Point2": "Luyện phát âm, độ lưu loát và cấu trúc câu",
  "inaugural.step2Point3": "Lặp lại bài tập nói nhiều lần tùy ý mà không áp lực",
  "inaugural.step2Point4": "Xây dựng sự tự tin trước khi nói với người khác",
  "inaugural.step2Footer": "Các buổi luyện tập ngắn, thường xuyên giúp học sinh hình thành thói quen nói và giảm lo lắng theo thời gian.",

  "inaugural.step3Title": "Buổi Học 1-1 Với Mentor",
  "inaugural.step3Timing": "Cuối tuần",
  "inaugural.step3Intro": "Cuối tuần—thường là Thứ Sáu hoặc cuối tuần—học sinh tham gia buổi học trực tuyến 1-1 với mentor bản xứ.",
  "inaugural.step3Point1": "Áp dụng những gì đã luyện tập trong tuần vào cuộc hội thoại thực",
  "inaugural.step3Point2": "Nói chuyện với người nghe mới nhưng thân thiện",
  "inaugural.step3Point3": "Tiếp xúc với cách sử dụng tiếng Anh tự nhiên và các giọng nói khác nhau",
  "inaugural.step3Point4": "Xây dựng sự tự tin chuyển đổi luyện tập thành giao tiếp thực",
  "inaugural.step3Footer": "Buổi học với mentor giúp học sinh \"nâng tầm\" bằng cách kết nối việc học trên lớp và luyện tập AI với tương tác thực tế.",

  "inaugural.sampleWeekTitle": "Lịch Trình Mẫu — Tuần 1",
  "inaugural.week1Focus": "Trọng Tâm Tuần 1",
  "inaugural.week1Theme": "Chủ đề: Bản thân & thế giới hàng ngày",
  "inaugural.week1Goal": "Mục tiêu nói: Học sinh tự giới thiệu ngắn gọn, có chuẩn bị mà không né tránh việc nói.",

  "inaugural.mondayTitle": "Thứ Hai",
  "inaugural.mondaySubtitle": "Buổi Học Với Giáo Viên Việt Nam",
  "inaugural.mondayFormat": "Hình thức: Lớp nhóm nhỏ (15 học sinh, 1 giáo viên)",
  "inaugural.learnPractice": "Học sinh học và luyện tập:",
  "inaugural.mondayPoint1": "Kỳ vọng và quy tắc rõ ràng: Sai lầm là điều bình thường và là một phần của việc học",
  "inaugural.mondayPoint2": "Tự giới thiệu có hướng dẫn sử dụng khung câu (ví dụ: \"Mình là...\", \"Mình thường...\", \"Mình thích...\")",
  "inaugural.mondayPoint3": "Nói theo cặp và nhóm nhỏ với thời gian chuẩn bị",
  "inaugural.mondayPoint4": "Giáo viên làm mẫu: cách dừng tự nhiên, cách do dự và tiếp tục nói, cách phục hồi khi không chắc chắn",
  "inaugural.competencyFocus": "Trọng tâm năng lực (Tuần 1):",
  "inaugural.competency1": "Nói: Tự giới thiệu có hỗ trợ",
  "inaugural.competency2": "Nghe để nói: Nghe các đoạn quen thuộc (tên, thói quen, sở thích)",
  "inaugural.competency3": "Tài nguyên ngôn ngữ: Từ vựng cá nhân tần suất cao; khung thì hiện tại đơn",
  "inaugural.competency4": "Phát âm & rõ ràng: Trọng âm từ; nói chậm hơn để rõ ràng",
  "inaugural.competency5": "Tự tin & chiến lược: Sử dụng từ đệm (\"để mình nghĩ\"), chấp nhận im lặng mà không dừng lại",

  "inaugural.tueThuTitle": "Thứ Ba–Thứ Năm",
  "inaugural.tueThuSubtitle": "Luyện Nói AI Hàng Ngày",
  "inaugural.tueThuFormat": "Hình thức: Buổi luyện tập ngắn hàng ngày (10–15 phút mỗi buổi) | Truy cập: Không giới hạn trong tuần",
  "inaugural.studentsDo": "Học sinh làm gì:",
  "inaugural.tueThuPoint1": "Luyện tự giới thiệu với các gợi ý AI ít áp lực",
  "inaugural.tueThuPoint2": "Lặp lại bài tập nói nhiều lần tùy ý",
  "inaugural.tueThuPoint3": "Xem trước và ôn lại từ vựng chính để sử dụng trên lớp",
  "inaugural.tueThuPoint4": "Luyện nói mà không sợ bị đánh giá",
  "inaugural.aiProvides": "AI cung cấp gì:",
  "inaugural.aiFeedbackDesc": "Phản hồi trung lập về nội dung, tập trung vào: hoàn thành, độ dài, rõ ràng (không phải độ chính xác ngữ pháp)",
  "inaugural.aiPurpose": "Mục đích của AI tuần này: Giúp học sinh ôn luyện nói an toàn và xây dựng sự thoải mái trước khi nói với người thật.",

  "inaugural.fridayTitle": "Thứ Sáu hoặc Cuối Tuần",
  "inaugural.fridaySubtitle": "Buổi Học 1-1 Với Mentor",
  "inaugural.fridayFormat": "Hình thức: Buổi học cá nhân với mentor bản xứ",
  "inaugural.inSession": "Trong buổi học:",
  "inaugural.fridayPoint1": "Xây dựng mối quan hệ qua hội thoại dựa trên chủ đề Tuần 1",
  "inaugural.fridayPoint2": "Học sinh tự giới thiệu và nói về cuộc sống hàng ngày",
  "inaugural.fridayPoint3": "Mentor phản ánh tích cực ngôn ngữ của học sinh",
  "inaugural.fridayPoint4": "Tập trung vào sự thoải mái, rõ ràng và khuyến khích",
  "inaugural.mentorsDoNot": "Mentor KHÔNG làm:",
  "inaugural.mentorNoDoDesc": "Không kiểm tra, không sửa nặng, không áp lực",
  "inaugural.mentorPurpose": "Mục đích của buổi học với mentor: Giúp học sinh chuyển đổi luyện tập thành giao tiếp thực với người nghe thân thiện.",

  "inaugural.week1Evidence": "Bằng Chứng & Kết Quả Tuần 1",
  "inaugural.byEndOfWeek1": "Cuối Tuần 1:",
  "inaugural.evidence1": "Học sinh hoàn thành bản ghi âm nói cơ sở",
  "inaugural.evidence2": "Học sinh hoàn thành tự đánh giá sự tự tin (S-FLCAS trước)",
  "inaugural.evidence3": "Giáo viên và mentor xác lập điểm xuất phát rõ ràng cho tiến độ",
  "inaugural.evidenceNote": "Bằng chứng này được sử dụng để hỗ trợ việc học, không phải để đánh giá hiệu suất.",

  "inaugural.exclusiveBenefits": "Quyền Lợi Độc Quyền",
  "inaugural.benefitsTitle": "Quyền Lợi Khóa Khai Giảng",
  "inaugural.benefitsDesc": "Nhóm sắp tới sẽ là khóa khai giảng của chúng tôi—những học sinh đầu tiên trải nghiệm chương trình nền tảng nói đầy đủ của Lingriser.",
  "inaugural.benefit1Title": "Hỗ trợ học phí",
  "inaugural.benefit1Desc": "Dành cho chương trình này",
  "inaugural.8weekProgram": "Chương trình 8 tuần",
  "inaugural.benefit2Title": "Ưu đãi học phí trọn đời",
  "inaugural.benefit2Desc": "Cho các chương trình Lingriser trong tương lai",
  "inaugural.benefitsFooter": "Những quyền lợi này ghi nhận các gia đình đặt niềm tin vào Lingriser khi chúng tôi ra mắt lộ trình học tập hoàn chỉnh.",

  "inaugural.registerTitle": "Đăng Ký Quan Tâm (Không Ràng Buộc)",
  "inaugural.registerSubtitle": "Biểu mẫu này không phải là đăng ký nhập học và không yêu cầu thanh toán.",
  "inaugural.registerNote": "Đăng ký quan tâm cho phép chúng tôi:",
  "inaugural.registerBenefit1": "Chia sẻ thông tin chi tiết đầy đủ về chương trình",
  "inaugural.registerBenefit2": "Liên hệ với bạn khi mở đăng ký",
  "inaugural.registerBenefit3": "Giữ quyền lợi khóa khai giảng cho bạn",
  "inaugural.parentName": "Họ tên phụ huynh",
  "inaugural.parentNamePlaceholder": "Nhập họ tên",
  "inaugural.phone": "Số điện thoại",
  "inaugural.phonePlaceholder": "Nhập số điện thoại",
  "inaugural.email": "Email",
  "inaugural.emailPlaceholder": "Nhập địa chỉ email",
  "inaugural.submit": "Đăng Ký Quan Tâm",
  "inaugural.submitting": "Đang gửi...",
  "inaugural.contactNote": "Chúng tôi sẽ liên hệ với bạn trước khi chương trình bắt đầu.",
  "inaugural.formSuccess": "Đã đăng ký thành công! Chúng tôi sẽ liên hệ với bạn sớm.",
  "inaugural.formError": "Có lỗi xảy ra. Vui lòng thử lại.",
  "inaugural.pleaseSelectIntent": "Vui lòng cho biết bạn có muốn đăng ký không.",
  "inaugural.primaryGoalQuestion": "Mục tiêu chính của bạn khi chọn chương trình cho con là gì?",
  "inaugural.goalAcademic": "Cải thiện kết quả học tập (điểm số, bài kiểm tra)",
  "inaugural.goalConfidence": "Xây dựng sự tự tin khi nói tiếng Anh",
  
  "inaugural.wantsToSignupQuestion": "Bạn có muốn đăng ký chương trình Speaking Foundation không?",
  "inaugural.yesInterested": "Có, tôi muốn đăng ký",
  "inaugural.noNotInterested": "Không, tôi chưa muốn đăng ký lúc này",
  "inaugural.whatInterestedYou": "Điều gì khiến bạn quan tâm đến chương trình? (Tùy chọn)",
  "inaugural.interestReasonPlaceholder": "Chia sẻ điều gì thu hút bạn nhất về chương trình này...",
  "inaugural.whyNotInterested": "Bạn có thể chia sẻ lý do không? Điều này sẽ giúp chúng tôi cải thiện. (Tùy chọn)",
  "inaugural.rejectionReasonPlaceholder": "Ví dụ: giá cả, thời gian không phù hợp, cần thêm thông tin...",

  // Instructor Section
  "inaugural.instructorTitle": "Giảng Viên Chương Trình",
  "inaugural.instructorSubtitle": "Học cùng chuyên gia giàu kinh nghiệm trong giảng dạy tiếng Anh",
  "inaugural.instructorName": "Thầy Trần Quốc Khải",
  "inaugural.instructorRole": "Giảng viên - Chương trình Speaking Foundation",
  "inaugural.qualifications": "Bằng cấp & Chứng chỉ",
  "inaugural.qual1": "Thạc sĩ Giảng dạy Tiếng Anh (TEFL/TESOL) - Đại học Cần Thơ",
  "inaugural.experience": "Kinh Nghiệm Giảng Dạy",
  "inaugural.exp1": "Hơn 6 năm kinh nghiệm giảng dạy tiếng Anh giao tiếp với video phim ảnh",
  "inaugural.instructorQuote": "Tôi tin rằng mọi học sinh đều có thể tự tin giao tiếp tiếng Anh khi được hướng dẫn đúng phương pháp và môi trường học tập phù hợp.",

  // Real Results
  "results.title": "Xem Kết Quả Thực Tế",
  "results.subtitle": "So sánh kỹ năng nói tiếng Anh trước và sau chương trình",
  "results.before": "Trước Chương Trình",
  "results.after": "Sau Chương Trình",
  "results.entryTest": "Bài kiểm tra đầu vào",
  "results.graduation": "Bài tốt nghiệp",
  "results.demoNote": "Các video được dùng cho mục đích minh họa, không phải học sinh thực tế.",
  "results.play": "Phát",
  "results.pause": "Tạm dừng",
  "results.mute": "Tắt tiếng",
  "results.unmute": "Bật tiếng",
  "results.viewProgram": "Xem Chương Trình",
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const t = (key: string): string => {
    return translations[key as keyof typeof translations] || key;
  };

  return <LanguageContext.Provider value={{ language: "vi", t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
